-- Bible Books
-- Total: 73 livros

INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (1, 'gn', 'Gênesis', 'Antigo Testamento', 1, 50);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (2, 'ex', 'Êxodo', 'Antigo Testamento', 2, 40);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (3, 'lv', 'Levítico', 'Antigo Testamento', 3, 27);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (4, 'nm', 'Números', 'Antigo Testamento', 4, 36);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (5, 'dt', 'Deuteronômio', 'Antigo Testamento', 5, 34);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (6, 'js', 'Josué', 'Antigo Testamento', 6, 24);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (7, 'jz', 'Juízes', 'Antigo Testamento', 7, 21);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (8, 'rt', 'Rute', 'Antigo Testamento', 8, 4);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (9, '1sm', 'I Samuel', 'Antigo Testamento', 9, 31);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (10, '2sm', 'II Samuel', 'Antigo Testamento', 10, 24);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (11, '1rs', 'I Reis', 'Antigo Testamento', 11, 22);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (12, '2rs', 'II Reis', 'Antigo Testamento', 12, 25);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (13, '1cr', 'I Crônicas', 'Antigo Testamento', 13, 29);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (14, '2cr', 'II Crônicas', 'Antigo Testamento', 14, 36);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (15, 'esd', 'Esdras', 'Antigo Testamento', 15, 10);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (16, 'ne', 'Neemias', 'Antigo Testamento', 16, 13);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (17, 'tb', 'Tobias', 'Antigo Testamento', 17, 14);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (18, 'jt', 'Judite', 'Antigo Testamento', 18, 16);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (19, 'et', 'Ester', 'Antigo Testamento', 19, 16);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (20, 'job', 'Jó', 'Antigo Testamento', 20, 42);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (21, 'sl', 'Salmos', 'Antigo Testamento', 21, 150);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (22, '1mc', 'I Macabeus', 'Antigo Testamento', 22, 16);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (23, '2mc', 'II Macabeus', 'Antigo Testamento', 23, 15);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (24, 'pv', 'Provérbios', 'Antigo Testamento', 24, 31);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (25, 'ec', 'Eclesiastes', 'Antigo Testamento', 25, 12);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (26, 'ct', 'Cântico dos Cânticos', 'Antigo Testamento', 26, 8);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (27, 'sb', 'Sabedoria', 'Antigo Testamento', 27, 19);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (28, 'eclo', 'Eclesiástico', 'Antigo Testamento', 28, 51);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (29, 'is', 'Isaías', 'Antigo Testamento', 29, 66);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (30, 'jr', 'Jeremias', 'Antigo Testamento', 30, 52);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (31, 'lm', 'Lamentações', 'Antigo Testamento', 31, 5);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (32, 'br', 'Baruc', 'Antigo Testamento', 32, 6);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (33, 'ez', 'Ezequiel', 'Antigo Testamento', 33, 48);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (34, 'dn', 'Daniel', 'Antigo Testamento', 34, 14);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (35, 'os', 'Oséias', 'Antigo Testamento', 35, 14);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (36, 'jl', 'Joel', 'Antigo Testamento', 36, 4);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (37, 'am', 'Amós', 'Antigo Testamento', 37, 9);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (38, 'ob', 'Abdias', 'Antigo Testamento', 38, 1);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (39, 'jn', 'Jonas', 'Antigo Testamento', 39, 4);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (40, 'mq', 'Miquéias', 'Antigo Testamento', 40, 7);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (41, 'na', 'Naum', 'Antigo Testamento', 41, 3);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (42, 'hc', 'Habacuc', 'Antigo Testamento', 42, 3);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (43, 'sf', 'Sofonias', 'Antigo Testamento', 43, 3);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (44, 'ag', 'Ageu', 'Antigo Testamento', 44, 2);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (45, 'zc', 'Zacarias', 'Antigo Testamento', 45, 14);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (46, 'ml', 'Malaquias', 'Antigo Testamento', 46, 3);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (47, 'sãomateus', 'São Mateus', 'Novo Testamento', 47, 28);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (48, 'sãomarcos', 'São Marcos', 'Novo Testamento', 48, 16);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (49, 'sãolucas', 'São Lucas', 'Novo Testamento', 49, 24);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (50, 'sãojoão', 'São João', 'Novo Testamento', 50, 21);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (51, 'atosdosapóstolos', 'Atos dos Apóstolos', 'Novo Testamento', 51, 28);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (52, 'rm', 'Romanos', 'Novo Testamento', 52, 16);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (53, '1co', 'I Coríntios', 'Novo Testamento', 53, 16);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (54, '2co', 'II Coríntios', 'Novo Testamento', 54, 13);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (55, 'gl', 'Gálatas', 'Novo Testamento', 55, 6);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (56, 'ef', 'Efésios', 'Novo Testamento', 56, 6);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (57, 'fl', 'Filipenses', 'Novo Testamento', 57, 4);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (58, 'cl', 'Colossenses', 'Novo Testamento', 58, 4);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (59, '1ts', 'I Tessalonicenses', 'Novo Testamento', 59, 5);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (60, '2ts', 'II Tessalonicenses', 'Novo Testamento', 60, 3);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (61, '1tm', 'I Timóteo', 'Novo Testamento', 61, 6);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (62, '2tm', 'II Timóteo', 'Novo Testamento', 62, 4);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (63, 'tt', 'Tito', 'Novo Testamento', 63, 3);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (64, 'filêmon', 'Filêmon', 'Novo Testamento', 64, 1);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (65, 'hb', 'Hebreus', 'Novo Testamento', 65, 13);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (66, 'sãotiago', 'São Tiago', 'Novo Testamento', 66, 5);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (67, 'isãopedro', 'I São Pedro', 'Novo Testamento', 67, 5);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (68, 'iisãopedro', 'II São Pedro', 'Novo Testamento', 68, 3);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (69, 'isãojoão', 'I São João', 'Novo Testamento', 69, 5);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (70, 'iisãojoão', 'II São João', 'Novo Testamento', 70, 1);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (71, 'iiisãojoão', 'III São João', 'Novo Testamento', 71, 1);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (72, 'sãojudas', 'São Judas', 'Novo Testamento', 72, 1);
INSERT INTO bible_books (id, abbrev, name, testament, book_order, total_chapters) VALUES (73, 'ap', 'Apocalipse', 'Novo Testamento', 73, 22);
