-- undefined (undefined)

-- Capítulo 1
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 1, 25);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 1, 'Tobias, da tribo e cidade de Neftali (que está situada na Galileia superior, acima de Naasson, por detrás do caminho que vai para o Ocidente, e tem à esquerda a cidade de Sefet),'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 2, 'foi levado cativo no tempo de Salmanasar, rei dos Assirios. Não obstante encontrar-se no cativeiro, não abandonou o caminho da verdade,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 3, 'de sorte que, daquilo de que podia dispor, distribuía todos os dias pelos seus irmãos de raça, que estavam cativos com ele.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 4, 'Embora fosse o mais jovem de todos os da tribo de Neftali, nada praticava de pueril em suas acções.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 5, 'Além disso, quando todos iam adorar os bezerros de ouro que Jeroboão, rei de Israel, tinha feito, só ele fugia da companhia de todos'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 6, 'e ia a Jerusalém ao templo do Senhor, onde adorava o Senhor Deus de Israel, oferecendo fielmente todas as suas primícias e os seus dízimos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 7, 'De três em três anos distribuía aos prosélitos e aos estrangeiros toda a dízima (destinada a eles).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 8, 'Estas e outras coisas semelhantes, segundo a Lei de Deus, observava desde menino.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 9, 'Quando chegou à idade varonil, casou-se com Ana, mulher da sua tribo, e teve dela um filho, a quem pôs o seu nome,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 10, 'ao qual ensinou desde a infância a temer a Deus e a abster-se de todo o pecado.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 11, 'Portanto, quando foi levado cativo com sua mulher e filho, para junto da sua tribo, na cidade de Nínive,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 12, 'ainda que todos comessem dos alimentos dos gentios, ele conservou pura a sua alma, não se manchou nunca com as suas comidas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 13, 'Porque ele de todo o seu coração se lembrou do Senhor, Deus concedeu-lhe graça diante do rei Salmanasar,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 14, 'o qual lhe deu permissão de ir aonde quisesse, com liberdade para fazer tudo o que lhe aprouvesse.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 15, 'Ia, pois, ter com todos os que estavam cativos, e dava-lhes conselhos salutares'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 16, 'Tendo, certo dia, ido a Ragés, cidade dos Medos, e levado dez talentos de prata, daquelas dádivas com que tinha sido presenteado pelo rei,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 17, 'ao ver em necessidade, entre a muita gente da sua nação, a Gabelo, que era da sua tribo, deu-lhe a sobredita quantia de prata, mediante um recibo da sua própria mão.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 18, 'Muito tempo depois, morto o rei Salmanasar, reinou, em seu lugar, Senaquerib, seu filho, o qual não podia ver os filhos de Israel.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 19, 'Tobias ia visitar diariamente todos os da sua parentela, consolava-os, e distribuía por cada um, dos seus bens, segundo as suas posses.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 20, 'Alimentava os famintos, vestia os nus e dava com solicitude sepultura aos que tinham falecido e aos que tinham sido mortos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 21, 'Finalmente, quando o rei Senaquerib se retirou, fugindo da Judeia à praga com que Deus o castigara pelas suas blasfémias, e, na sua ira, mandou matar muitos dos filhos de Israel, Tobias sepultava os seus cadáveres.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 22, 'Quando o rei teve conhecimento disto, mandou que o matassem e confiscou todos os seus bens.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 23, 'Tobias, porém, despojado de tudo, fugindo com seu filho e com sua mulher, escondeu-se, porque muitos lhe queriam bem.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 24, 'Passados quarenta e cinco dias, assassinaram o rei seus próprios filhos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 25, 'Então Tobias voltou para sua casa, e todos os seus bens lhe foram restituídos.');

-- Capítulo 2
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 2, 23);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 1, 'Depois disto, num dia de festa do Senhor, estando preparado um grande banquete em casa de Tobias,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 2, 'disse este a seu filho: Vai e traz aqui alguns da nossa tribo, que sejam tementes a Deus, para comerem connosco.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 3, 'Tendo ele ido, na volta contou ao pai que um dos filhos de Israel jazia degolado na rua. Imediatamente Tobias, levantando-se da mesa, sem nada haver comido, foi junto do cadáver,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 4, 'tomou-o e levou-o secretamente para sua casa, a fim de, depois do sol posto, o sepultar com precaução.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 5, 'Depois de ter escondido o cadáver, pôs-se a comer com pranto e tremor,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 6, 'recordando-se do que o Senhor tinha dito por meio do profeta Amós: Os vossos dias de festa converter-se-ão em lamentação e pranto.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 7, 'Após o sol posto, saiu e sepultou-o.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 8, 'Todos os seus vizinhos o arguiam, dizendo: Já por este motivo te mandaram matar; mal escapaste da sentença de morte, logo recomeças a sepultar os mortos?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 9, 'Porém Tobias, temendo mais a Deus do que ao rei, levava os corpos dos que tinham sido mortos, escondia-os em sua casa e sepultava-os pelo meio da noite.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 10, 'Sucedeu um dia que, cansado de enterrar mortos, ao chegar a sua casa deitou-se junto duma parede e adormeceu.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 11, 'Enquanto dormia, caiu-lhe dum ninho de andorinhas um pouco de esterco quente sobre os olhos, e ficou cego.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 12, 'O Senhor permitiu que lhe acontecesse esta prova, para que a sua paciência servisse assim de exemplo aos vindouros, como a do santo Job.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 13, 'Como havia sempre temido a Deus, desde a sua infância, e guardado os seus mandamentos, não se entristeceu contra Deus, por lhe ter acontecido a desgraça da cegueira.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 14, 'Permaneceu firme no temor de Deus, dando-lhe graças todos os dias da sua vida.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 15, 'Assim como os reis (ou poderosos) insultavam o bem-aventurado Job, assim os parentes e amigos de Tobias escarneciam da sua conduta, dizendo:'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 16, 'Onde está a tua esperança, pela qual davas esmolas e sepultavas os mortos?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 17, 'Porém Tobias os repreendia; Não faleis assim,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 18, 'porque nós somos filhos dos santos (patriarcas) e esperamos aquela vida que Deus hã-de dar aos que nunca deixam de confiar nele.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 19, 'Ana, sua mulher, ia todos os dias tecer, e do trabalho das suas mãos trazia o que podia ganhar para viver.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 20, 'Assim aconteceu que, tendo recebido um cabrito, levou-o para casa'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 21, 'seu marido, tendo-o ouvido dar balidos, disse: Vede que não seja furtado; restituí-o a seus donos, porque a nós não nos é lícito comer nem tocar coisa alguma furtada.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 22, 'A isto respondeu-lhe sua mulher com ira: Bem claro está que as tuas esperanças são vãs! Agora mostram o que valem as tuas esmolas!'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 23, 'Com estas e outras palavras semelhantes o insultava.');

-- Capítulo 3
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 3, 25);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 1, 'Então Tobias deu um suspiro e começou a orar com lágrimas,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 2, 'dizendo: Tu és justo, Senhor, todos os teus juízos são justos, todos os teus caminhos são misericórdia, verdade e justiça.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 3, 'Agora, pois, Senhor, lembra-te de mim, não tomes vingança dos meus pecados, não te lembres dos meus delitos nem dos de meus pais.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 4, 'Porque não obedecemos aos teus preceitos, por isso fomos entregues ao saque, ao cativeiro e à morte, e tornamo-nos objecto de riso e opróbrio para todas as nações, por entre as quais nos espaIhaste.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 5, 'Agora, Senhor, os teus castigos são grandes, porque nós não procedemos segundo os teus preceitos, não andámos sinceramente na tua presença.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 6, 'Senhor, trata-me segundo a tua vontade, mas manda que o meu espírito seja recebido em paz, porque é melhor para mim morrer do que viver.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 7, 'Naquele mesmo dia aconteceu que Sara, filha de Raguel, que estava em Ecbatana, cidade dos Medos, ouviu-se ultrajar por uma das criadas de seu pai,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 8, 'porque tinha sido casada com sete maridos, e um demônio chamado Asmodeu os tinha morto, quando eles se aproximavam dela.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 9, 'Tendo Sara repreendido a criada por uma falta qualquer, ela respondeu-lhe: Não vejamos nós jamais sobre a terra filho nem filha nascida de ti, ó assassina dos teus maridos!'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 10, 'Porventura queres tu também matar-me a mim, como já mataste sete maridos? A estas palavras subiu Sara ao quarto mais alto da sua casa e durante três dias e três noites não comeu nem bebeu.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 11, 'Perseverando em oração, pedia a Deus com lágrimas, que a livrasse deste opróbrio.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 12, 'Ao terceiro dia, acabou a oração bendizendo o Senhor, assim:'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 13, 'Bendito é o teu nome, ó Deus de nossos pais, que, depois de te irares, usas de misericórdia, e no tempo da aflição perdoas os pecados aos que te invocam.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 14, 'Para ti, Senhor, volto a minha face, para ti dirijo os meus olhos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 15, 'Peço-te, Senhor, que me livres do laço desta ignomínia, ou que, ao menos, me tires do cimo da terra.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 16, 'Tu sabes, Senhor, que eu nunca desejei (ilicitamente) nenhum homem, que conservei a minha alma pura de toda a concupiscência.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 17, 'Nunca acompanhei com gente licenciosa, nem tive comércio com os que se portam com leviandade.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 18, 'Consenti em tomar marido por teu temor, e não por paixão.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 19, 'Ou eu fui indigna deles, ou porventura eles não foram dignos de mim; talvez me tenhas reservado para outro marido (da minha mesma tribo de Neftali).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 20, 'Não está ao alcance dos homens (perscrutar) os teus desígnios.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 21, 'Todavia todo o que te rende culto tem por certo que a sua vida, se for provada, será coroada; se for atribulada, será livre; se for castigada, poderá acolher-se à tua misericórdia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 22, 'Com efeito, tu não te deleitas com a nossa perdição: depois da tormenta, dás a bonança, depois das lágrimas e suspiros, infundes a alegria.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 23, 'Seja o teu nome, ó Deus de Israel, bendito pelos séculos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 24, 'Foram ouvidas, ao mesmo tempo, as orações de ambos, diante da majestade do sumo Deus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 25, 'Rafael, santo anjo do Senhor, foi enviado para curar Tobias e Sara, cujas orações tinham sido apresentadas simultaneamente diante do Senhor.');

-- Capítulo 4
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 4, 23);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 1, 'Julgando Tobias que seria ouvida a oração que tinha feito e que ia morrer, chamou para junto dele seu filho Tobias'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 2, 'e disse-lhe: Ouve, meu filho, as palavras da minha boca e põe-nas no teu coração, como um sólido fundamento.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 3, 'Depois que Deus tiver recebido a minha alma, sepulta o meu corpo. Honra tua mãe durante todos os dias da sua vida,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 4, 'porque te deves lembrar de quantos e quão grandes perigos padeceu por amor de ti, trazendo-te no seu ventre.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 5, 'Quando ela tiver também acabado o tempo da sua vida, sepultá-la-ás junto de mim.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 6, 'Tem a Deus em teu espírito todos os dias da tua vida; guarda-te de consentir jamais no pecado, de violar os preceitos do Senhor nosso Deus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 7, 'Dá esmola dos teus bens, e não voltes a tua cara a nenhum pobre, porque desta sorte sucederá que também não se apartará de ti a face do Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 8, 'Da maneira que puderes, sê misericordioso.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 9, 'Se tiveres muito, dá muito; se tiveres pouco, procura dar de boamente também esse pouco.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 10, 'Assim entesourarás uma grande recompensa para o dia da necessidade,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 11, 'porque a esmola livra de todo o pecado e da morte (eterna), e não deixará cair a alma nas trevas (do inferno). (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 12, 'A esmola será motivo de grande confiança diante do sumo Deus, para todos os que a dão.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 13, 'Preserva-te, meu filho, de toda a fornicação (ou impureza), e, fora da tua mulher, nunca consintas em conhecer o crime (de te unir a outra).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 14, 'Nunca permitas que a soberba domine nos teus pensamentos ou nas tuas palavras, porque nela teve principio toda a perdição.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 15, 'A todo o homem que tiver feito algum trabalho, paga-lhe logo o salário, e nunca fique, um instante, em teu poder a paga do trabalhador.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 16, 'Acautela-te, não faças nunca a outro o que não quererias que outro te fizesse.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 17, 'Come o teu pão (repartindo-o) com os pobres e com os que têm fome, e veste com as tuas roupas os que estão nus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 18, 'Põe o teu pão e o teu vinho sobre a sepultura do justo, e não o comas nem bebas com os pecadores.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 19, 'Pede sempre conselho ao sábio.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 20, 'Bendiz a Deus em todo o tempo, pede-lhe que dirija os teus caminhos e que todos os teus projectos se firmem nele.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 21, 'Também te faço saber, meu filho, que, quando ainda eras criança, emprestei dez talentos de prata a Gabelo, em Ragés, cidade dos Medos, e que tenho em meu poder o seu recibo;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 22, 'por isso busca o modo de ir ter com ele e cobrar a sobredita quantia de dinheiro, entregando-lhe o seu recibo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 23, 'Não temas, meu filho; é verdade que vivemos pobres, mas teremos muitos bens, se temermos a Deus, se nos desviarmos de todo o pecado, se procedermos bem.');

-- Capítulo 5
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 5, 28);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 1, 'Então Tobias respondeu a seu pai: Meu pai, farei tudo o que me mandaste.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 2, 'Todavia não sei de que modo poderei cobrar este dinheiro, porque nem ele lhe conhece a mim, nem eu o conheço a ele; que sinal lhe hei-de dar? Nem mesmo sei o caminho, por onde se vai a tal terra.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 3, 'Então seu pai disse-lhe: Eu tenho em meu poder o recibo do seu próprio punho; quando tu lho mostrares, ele te pagará logo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 4, 'Portanto agora vai e busca algum homem fiel, que te acompanhe, mediante uma retribuição, para que cobres o dinheiro enquanto eu estou vivo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 5, 'Mal havia Tobias saído (de casa), logo encontrou um jovem de belo aspecto, que estava cingido e como prestes a caminhar.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 6, 'Não sabendo que era um anjo de Deus, saudou-o e disse: Donde és tu ó bom jovem?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 7, 'Ele respondeu: Eu sou dos filhos de Israel. Tobias perguntou-lhe: Conheces o caminho que conduz à terra dos Medos?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 8, 'O anjo respondeu-lhe: Conheço: tenho percorrido muitas vezes estes caminhos e tenho estado em casa de Gabelo, nosso irmão, que mora em Ragés, cidade dos Medos, que está situada sobre o monte de Ecbatana.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 9, 'Tobias disse-lhe: Suplico-te que esperes por mim, até que eu avise meu pai disto mesmo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 10, 'Então Tobias, tendo entrado, referiu a seu pai o sucedido. O pai, admirado com isto, rogou-lhe que entrasse em sua casa.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 11, 'Tendo, pois, entrado, saudou a Tobias, e disse: A alegria seja sempre contigo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 12, 'Tobias respondeu: Que alegria poderei eu ter, eu que sempre estou em trevas, que não vejo a luz do céu?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 13, 'O jovem disse-lhe: Tem ânimo! É fácil a Deus curar-te.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 14, 'Disse-lhe, pois, Tobias: Porventura poderás tu conduzir meu filho a casa de Gabelo, em Ragés, cidade dos Medos? Quando voltares, eu te pagarei o teu trabalho.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 15, 'O anjo respondeu: Eu lá o conduzirei, e to reconduzirei.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 16, 'Tobias, então, perguntou-lhe: Peço-Te que me digas: de que família e de que tribo és tu?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 17, 'O anjo Rafael respondeu: Procuras conhecer a família do mercenário, ou o próprio mercenário, que vá com teu filho?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 18, 'Mas, para que te não ponha em cuidados, eu sou Azarias, filho do grande Ananias.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 19, 'Tobias respondeu-lhe: Tu és de uma ilustre família. Peço-te que te não ofendas por eu ter desejado conhecer a tua família.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 20, 'O anjo disse-lhe: Eu conduzirei são o teu filho, e são to reconduzirei.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 21, 'Tobias respondeu: Fazei boa jornada! Deus seja convosco no vosso caminho, e o seu anjo vos acompanhe.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 22, 'Então, preparando tudo o que deviam levar na jornada, Tobias despediu-se de seu pai e de sua mãe e pôs-se a caminho com o anjo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 23, 'Logo que partiram, começou sua mãe a chorar e a dizer: Tu tiraste-nos o bordão da nossa velhice, tu o apartaste de nós.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 24, 'Osalá que nunca tivesse havido este dinheiro, por causa do qual tu o mandaste.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 25, 'A nossa pobreza bastava-nos, e era para nós uma riqueza o vermos nosso filho.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 26, 'Tobias disse-lhe: Não chores; nosso filho chegará salvo, voltará salvo para a nossa companhia, e tu o verás com os teus olhos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 27, 'Eu creio que um bom anjo de Deus o acompanha e dispõe tudo o que lhe diz respeito, de modo que voltará para nós cheio de alegria.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 28, 'A estas palavras a mãe cessou de chorar e calou-se.');

-- Capítulo 6
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 6, 22);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 1, 'Partiu, pois, Tobias, seguido do seu cão, e parou na primeira pousada junto do rio Tigre.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 2, 'Quando saiu a lavar os pés, avançou da água um enorme peixe para o devorar.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 3, 'A sua vista, Tobias, espavorido, clamou em alta voz, dizendo; Senhor, ele lança-se a mim.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 4, 'O anjo disse-lhe: Pega-lhe pelas guelras e puxa-o para ti. Tendo-o assim feito, puxou-o para terra, e o peixe começou a palpitar a seus pés.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 5, 'Então disse-lhe o anjo: Tira as entranhas a esse peixe, e guarda o coração, o fel e o fígado, porque estas coisas te servirão para remédios eficazes'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 6, 'Feito isto, assou Tobias parte da sua carne, que levaram consigo para o caminho; salgaram o resto, para que lhes bastasse até chegarem a Ragés, cidade dos Medos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 7, 'Então Tobias perguntou ao anjo: Irmão Azarias, suplico-te que me digas para que remédio servirão estas partes do peixe, que tu me mandastes guardar?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 8, 'O anjo respondeu: Se tu puseres um pedacinho do seu coração sobre brasas acesas, o seu fumo afugenta toda a casta de demónios, tanto do homem, como da mulher, de sorte que não tornam mais a chegar a eles. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 9, 'Quanto ao fel, é bom untar os olhos que têm algumas névoas, tem a propriedade de os curar.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 10, 'Tobias disse-lhe: Onde queres que pousemos?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 11, 'O anjo respondeu: Há aqui um homem, chamado Raguel, teu parente, da tua tribo, que tem uma filha chamada Sara; além dela, não tem mais filho nem filha.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 12, 'Todos os seus bens te devem pertencer, mas é preciso que a recebas por mulher. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 13, 'Pede-a, pois, a seu pai, e ele la dará em casamento.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 14, 'Então Tobias replicou: Eu sei que ela foi já casada com sete maridos, e que todos morreram; também soube que um demónio os matou.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 15, 'Temo que me suceda também o mesmo e que, como sou filho único de meus pais, faça descer a sua velhice com tristeza ao sepulcro.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 16, 'Então o anjo Rafael disse-lhe: Ouve-me, que eu te mostrarei quais são aqueles sobre quem o demónio tem poder.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 17, 'São os que se casam com tais disposições que lançam a Deus fora do seu coração e do seu espírito, e se entregam à sua paixão, como o cavalo e o macho, que não têm entendimento: é sobre estes que o demónio tem poder.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 18, 'Porém tu, quando a tiveres recebido, tendo entrado na câmara, viverás com ela em continência durante três dias, e não cuidarás noutra coisa que em fazer oração com ela.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 19, 'No decurso da primeira noite, queimando o fígado do peixe, será posto em fuga o demónio.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 20, 'Na segunda noite serás admitido na sociedade dos santos patriarcas. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 21, 'E na terceira noite conseguirás a bênção, para que de vós nasçam filhos robustos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 22, 'Passada a terceira noite, tomarás a donzela no temor do Senhor, levado mais pelo desejo de ter filhos, do que por sensualidade, a fim de conseguires nos teus filhos a bênção reservada à descendência de Abraão.');

-- Capítulo 7
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 7, 20);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 1, 'Entraram, pois, em casa de Raguel, que os recebeu com alegria.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 2, 'Pondo Raguel os olhos em Tobias, disse para Ana, sua mulher: Como este jovem é parecido com meu primo!'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 3, 'Dito isto, perguntou: Donde sois vós, ó jovens nossos irmãos? Eles responderam : Somos da tribo de Neftali, dos cativos de Ninive.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 4, 'Raguel disse-lhes: Vós conheceis meu irmão Tobias? Eles responderam: Conhecemos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 5, 'Como Raguel fizesse o elogio de Tobias. o anjo disse a Raguel: Esse Tobias, por quem perguntas, é o pai deste jovem.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 6, 'Raguel correu para ele, abraçou-o com lágrimas, chorando sobre o seu pescoço.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 7, 'Abençoado sejas, disse, meu filho, porque és filho de um homem de bem e virtuosíssimo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 8, 'Ana, sua mulher, e Sara, sua filha, derramavam lágrimas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 9, 'Depois que falaram, mandou Raguel matar um carneiro e preparar um banquete. Quando ele os rógava que se pusessem à mesa,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 10, 'Tobias disse: Eu não comerei nem beberei aqui hoje, antes que tu me não despaches a minha petição, prometendo dar-me Sara, tua filha.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 11, 'Ouvindo isto, Raguel assustou-se, sabendo o que tinha acontecido aos sete maridos que se tinham aproximado dela, e começou a temer que sucedesse também o mesmo a este. Como vacilasse e não desse resposta alguma à petição de Tobias.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 12, 'o anjo disse-lhe: Não temas dar tua filha a este jovem, porque a este, que é temente a Deus, é devida a tua filha como esposa. Por isso nenhum outro a pode ter.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 13, 'Então Raguel respondeu: Não duvido que Deus aceitasse em sua presença as minhas orações e as minhas lágrimas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 14, 'Creio que ele fez que viésseis ter comigo, para que está filha se desposasse com um da sua parentela, segundo a lei de Moisés, Portanto não duvides que eu ta darei.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 15, 'E, pegando na mão direita de sua filha, a pôs na mão direita de Tobias, dizendo: O Deus de Abraão, o Deus de Isaac o Deus de Jacob seja convosco, que ele mesmo vos ajunte e cumpra em vós a sua bênção.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 16, 'Depois, tomando papel, fizeram a escritura de casamento.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 17, 'Tomaram parte no banquete, bendizendo a Deus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 18, 'Raguel chamou Ana, sua mulher, e ordenou-Ihe que preparasse outro aposento.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 19, '(Ana) introduziu lá Sara, sua filha, e pôs-se a chorar.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 20, 'E disse-lhe: Tem ânimo, minha filha; o Senhor do céu te encha de alegria pelos desgostos que tens sofrido.');

-- Capítulo 8
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 8, 24);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 1, 'Depois de terem ceado, introduziram o jovem no aposento da esposa.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 2, 'Tobias, lembrando-se do que lhe tinha dito o anjo, tirou da sua bolsa um pedaço de fígado de peixe e colocou-o sobre uns carvões acesos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 3, 'Nessa altura, o anjo Rafael pegou no demónio e ligou-o no deserto do alto Egipto.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 4, 'Então Tobias encorajou a jovem com estas palavras; Sara, levanta-te e façamos oração a Deus, hoje, amanhã e depois de amanhã. Nestas três noites nos uniremos a Deus; depois da terceira noite, viveremos no nosso matrimónio,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 5, 'porque nós somos filhos de santos, e não podemos juntar-nos à maneira dos Gentios que não conhecem a Deus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 6, 'Levantando-se ambos, oravam juntos com fervor para que lhes fosse conservada a vida.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 7, 'Tobias disse: Senhor Deus de nossos pais, bendigam-te o céu e a terra, o mar, as fontes, os rios e todas as tuas criaturas que neles se encerram.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 8, 'Tu fizeste Adão do limo da terra, e deste-lhe Eva por companheira.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 9, 'Ora tu sabes, Senhor, que não é por motivo de paixão que eu tomo esta minha irmã por esposa, mas só pelo desejo de ter filhos, pelos quais o leu nome seja bendito pelos séculos dos séculos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 10, 'E Sara disse : Compadece-te de nós, Senhor, compadece-te de nós, e faz que vivamos juntos até à velhice em perfeita saúde.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 11, 'Ao cantar do galo, Raguel mandou chamar os seus criados, que foram com ele abrir uma sepultura.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 12, 'Pode ser, dizia, que tenha acontecido a este o mesmo que aos outros sete homens que estiveram com ela.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 13, 'Depois que prepararam a cova, voltou Raguel para junto de sua mulher e disse-lhe:'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 14, 'Manda uma das tuas criadas ver se ele morreu, para o sepultar antes que amanheça.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 15, 'Ela mandou uma das suas criadas. Esta, tendo entrado na câmara, achou-os sãos e salvos, dormindo juntamente.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 16, 'Voltando, deu esta boa nova, e, então, tanto Raguel como Ana, sua mulher, louvaram o Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 17, 'Disseram : Nós te bendizemos. Senhor Deus de Israel, por não ter sucedido o que julgávamos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 18, 'Usaste connosco da tua misericórdia, lançando para longe de nós o inimigo que nos perseguia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 19, 'Tiveste compaixão de dois filhos únicos. Faz, Senhor, que eles te bendigam mais e mais, e te ofereçam um sacrifício de louvor pela sua saúde, a fim de que todas as nações conheçam que só tu és o Deus em toda a terra.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 20, 'Raguel mandou logo aos seus criados que enchessem a cova, que tinham feito, antes que fosse dia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 21, 'Disse a sua mulher que aprontasse um banquete e preparasse tudo o que era necessário aos viajantes, para seu sustento.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 22, 'Também mandou matar duas vacas gordas e quatro carneiros, destinados a um banquete para todos os seus vizinhos e para todos os amigos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 23, 'Raguel instou com Tobias para que ficasse com ele duas semanas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 24, 'De tudo o que possuía, Raguel deu metade a Tobias, e declarou por escrito que a outra metade passaria a Tobias depois da sua morte e da de sua mulher.');

-- Capítulo 9
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 9, 12);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 1, 'Então Tobias chamou a si o anjo, que ele julgava ser homem, e disse-lhe: Irmão Azarias, peço-te que ouças as minhas palavras.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 2, 'Ainda que eu me entregasse a ti por escravo, não poderia corresponder dignamente aos teus cuidados.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 3, 'Suplico-te, não obstante, que tomes contigo cavalgaduras e servos, e vás ter com Gabelo, a Ragés, cidade dos Medos. Entrega-Ihe o seu recibo, recebe dele o dinheiro e roga-lhe que venha à minha boda.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 4, 'Tu bem sabes que meu pai conta os dias: se eu tardar um dia mais, a sua alma se contristará.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 5, 'Tu vês também como Raguel instou comigo, e que não posso desprezar as suas instâncias tão fortes.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 6, 'Então Rafael, tomando quatro criados de Raguel e dois camelos, foi à cidade de Ragés, na Média. Encontrando Gabelo, entregou-lhe o seu recibo, e recebeu dele todo o dinheiro.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 7, 'Contou-lhe tudo o que tinha sucedido a Tobias, filho de Tobias, e fê-lo ir consigo à boda.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 8, 'Tendo Gabelo entrado em casa de Raguel, encontrou Tobias à mesa. Levantando-se este, beijaram-se mutuamente; Gabelo chorou e louvou a Deus,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 9, 'dizendo: O Deus de Israel te abençoe, porque és filho dum homem óptimo, justo, temente a Deus e esmoler;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 10, 'estenda-se também a bênção a tua mulher e a vossos pais;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 11, 'possais ver os vossos filhos e os filhos de vossos filhos, até à terceira e quarta geração! Seja a vossa descendência bendita do Deus de Israel, que reina pelos séculos dos séculos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 12, 'Tendo todos respondido: Amen — puseram-se à mesa. Foi também com o temor do Senhor que celebraram o banquete nupcial.');

-- Capítulo 10
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 10, 13);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 1, 'Enquanto Tobias se demorava, por causa das núpcias, seu pai Tobias estava em cuidados, dizendo: Quem sabe por que motivo tarda meu filho, por que se tem lá detido?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 2, 'Porventura morreria Gabelo, e não haverá ninguém que lhe restitua o dinheiro?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 3, 'Começou ele, pois, a entristecer-se em extremo, e Ana, sua mulher, com ele ; ambos juntos começaram a chorar, porque seu filho não voltava no tempo marcado.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 4, 'Sobretudo sua mãe derramava lágrimas inesgotáveis e dizia: Ai, ai de mim! meu filho, para que te mandamos nós tão longe, a ti que eras a luz dos nossos olhos, o bordão da nossa velhice, a consolação da nossa vida e a esperança da nossa posteridade?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 5, 'Nós, que em ti só tínhamos tudo, não devíamos afastar-te da nossa companhia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 6, 'Tobias dizia-lhe: Cala-te, não te perturbes, que o nosso filho está são ; aquele homem, com quem nós o mandamos, é muito fiel.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 7, 'Ela, porém, não se podia consolar de modo algum, mas, saindo todos os dias fora, andava olhando para todas as parles, e corria por todos os caminhos, por onde esperava que o filho poderia voltar, para o ver vir ao longe, se lhe fosse possível.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 8, 'Entretanto Raguel dizia a seu genro: Fica-te aqui; eu mandarei a Tobias, teu pai, um mensageiro com novas da tua saúde.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 9, 'Tobias respondeu-lhe: Eu sei que meu pai e minha mãe estão agora contando-os dias e que o seu espírito está num continuo tormento.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 10, 'Raguel, depois de ter feito muitas instâncias a Tobias, ao ver que este não queria, de modo algum, condescender com ele, entregou-lhe sua filha Sara e metade de tudo o que possuía em servos, servas, rebanhos, camelos, vacas, e em grande quantidade de dinheiro; (depois)deixou-o partir são e alegre,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 11, 'dizendo: Que o santo anjo do Senhor seja convosco na viagem, vos conduza sem perigo algum, e que os meus olhos vejam os vossos filhos antes de eu morrer.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 12, 'Os pais, abraçando a sua filha, beijaram-na e deixaram-na partir,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 13, 'recomendando-lhe que honrasse os seus sogros, que amasse o seu marido, que regesse a sua família, que governasse a sua casa, conservando-se ela própria irrepreensível.');

-- Capítulo 11
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 11, 21);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 1, 'De regresso, chegaram no undécimo dia a Caran, que está no meio do caminho para Nínive.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 2, 'O anjo disse: Irmão Tobias, tu sabes o estado em que deixaste teu pai.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 3, 'Se assim, pois, te parece bem, vamos nós adiante, e os teus domésticos sigam-nos devagar com tua mulher e com os gados'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 4, 'Tendo Tobias achado bom este parecer, disse-lhe Rafael: Traz contigo do fel do peixe, porque será necessário. Tomou, portanto, Tobias do fel, e partiram.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 5, 'Entretanto Ana todos os dias se ia assentar junto da estrada, no alto duma colina, donde podia ver ao longe,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 6, 'Enquanto desse lugar espreitava a sua vinda, viu ao longe e logo reconheceu seu filho que vinha; (logo) correu a dar a nova a seu marido, dizendo: Eis ai vem teu filho.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 7, 'Ao mesmo tempo Rafael disse a Tobias: Quando tiveres entrado em tua casa, adora logo ao Senhor teu Deus e dá-lhe graças; depois aproxima-te de teu pai e dá-lhe um beijo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 8, 'Unta-lhe imediatamente os seus olhos com este fel do peixe, que trazes contigo, porque está certo que logo os seus olhos se abrirão, que teu pai verá a luz do céu e se alegrará em te ver,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 9, 'Então o cão, que os tinha seguido pelo caminho, correu adiante e, como que trazendo a nova, mostrava o seu contentamento e fazia festas, abanando a cauda.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 10, 'O pai, levantando-se, começou a correr cego, tropeçando. Dando, então, a mão a um criado, foi ao encontro de seu filho.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 11, 'Abraçou-o e beijou-o, fazendo o mesmo sua mulher, e ambos começaram a chorar de alegria.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 12, 'Depois que adoraram a Deus e lhe deram graças, assentaram-se.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 13, 'Então Tobias, tomando do fel do peixe, untou os olhos de seu pai.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 14, 'Esperou quase meia hora, e, (então), começou a sair de seus olhos uma belida, como a película dum ovo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 15, 'Tobias, pegando nela, tirou-a dos olhos do pai, que imediatamente recobrou a vista,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 16, 'E glorificaram a Deus, ele, sua mulher e todos os que ó conheciam.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 17, 'Tobias dizia: Eu te bendigo. Senhor Deus de Israel, por me teres castigado e por me teres curado; eis que vejo o meu filho Tobias!'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 18, 'Passados sete dias, chegou também Sara, mulher de seu filho, com todos os seus servidores, de boa saúde, com os rebanhos, os camelos, o grande dote do seu casamento e com o dinheiro restituído por Gabelo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 19, 'Tobias contou a seus pais todos os benefícios que Deus Ihe tinha feito, por meio desse homem, que o conduzira.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 20, 'Aquior e Nabat, primos de Tobias, foram regozijar-se com Tobias, congratular-se com ele por todos os favores que Deus lhe tinha feito.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 21, 'Banqueteando-se durante sete dias, todos se regozijaram com a maior alegria.');

-- Capítulo 12
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 12, 22);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 1, 'Então Tobias chamou seu filho e disse-lhe: Que podemos nós dar a este santo homem que te acompanhou ?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 2, 'Ele respondeu: Meu pai, que galardão lhe daremos nós? que coisa poderá haver proporcionada aos seus benefícios?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 3, 'Ele levou-me e trouxe-me são e salvo; recebeu de Gabelo o dinheiro; fez-me ter mulher e afugentou dela o demónio; encheu de alegria os seus pais; livrou-me a mim mesmo de ser tragado pelo peixe; a ti fez-te ver a luz do céu: por ele nós fomos cheios de todos os bens. Que lhe poderemos dar que iguale tais benefícios?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 4, 'Rogo-te, meu pai, que lhe peças se digne tomar para si metade de tudo o que trouxemos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 5, 'O pai e o filho chamaram-no, pois, à parte, e começaram a rogar-lhe que se dignasse aceitar metade de tudo o que tinham trazido.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 6, 'Então ele falou-lhes particularmente; Bendizei o Deus do céu, dai-lhe glória diante de todos os viventes, por ter usado convosco da sua misericórdia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 7, 'E bom conservar escondido o segredo do rei, mas é coisa louvável manifestar e publicar as obras de Deus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 8, 'E boa a oração acompanhada do jejum, e dar esmola vale mais do que juntar tesouros de ouro,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 9, 'porque a esmola livra da morte (eterna): apaga os pecados e faz encontrar a misericórdia e a vida eterna.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 10, 'Mas os que cometem pecado e iniquidade, são inimigos das suas almas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 11, 'Eu vou descobrir-vos a verdade, não quero ocultar-vos nada.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 12, 'Quando tu oravas com lágrimas, enterravas os mortos, quando deixavas o teu jantar, para esconder os mortos em tua casa de dia, e os enterrar de noite, eu apresentei as tuas orações ao Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 13, 'Porque tu eras aceito a Deus, por isso foi necessário que a tentação te provasse.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 14, 'Agora o Senhor enviou-me a curar-te e a livrar do demônio a Sara, mulher de teu filho.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 15, 'Eu sou o anjo Rafael, um dos sete (espíritos principais) que assistimos diante do Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 16, 'Ao ouvir estas palavras, ficaram fora de si, e, tremendo, caíram com o rosto em terra.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 17, 'O anjo disse-lhe: A paz seja convosco, não temais.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 18, 'Quando eu estava convosco, eu o estava por vontade de Deus; bendizei-o, cantai-lhe louvores.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 19, 'Parecia-vos que eu comia e bebia convosco, mas eu sustento-me dum manjar invisível, duma bebida (que consiste na visão de Deus) a qual não pode ser vista pelos homens.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 20, 'É , pois, tempo que eu volte para aquele que me enviou; vós, porém, bendizei a Deus, e contai todas as suas maravilhas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 21, 'Proferidas estas palavras, desapareceu diante deles, e eles não o puderam ver mais.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 22, 'Então prostrando-se com o rosto por terra durante três horas, bendisseram a Deus; depois, erguendo-se, publicaram todas as suas maravilhas.');

-- Capítulo 13
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 13, 23);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 1, 'O velho Tobias, abrindo a sua boca, disse ao Senhor, assim: Tu, Senhor, es grande na eternidade, e o teu reino estende-se por todos os séculos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 2, 'Com efeito, tu castigas e salvas, conduzes até ao sepulcro e ressuscitas, e ninguém há que possa subtrair-se á tua mão.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 3, 'Dai graças ao Senhor, filhos de Israel, e louvai-o diante das nações,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 4, 'porque ele vos espalhou por entre os povos que o não conhecem, a fim de que vós publiqueis as suas maravilhas, e lhes façais saber que não há outro Deus omnipotente senão ele.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 5, 'Ele castigou-nos por causa das nossas iniquidades, e ele mesmo nos salvará pela sua misericórdia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 6, 'Considerai, pois, o que ele fez connosco, e bendizei-o com temor e tremor, exaltai o rei dos séculos com as vossas obras.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 7, 'Eu lhe darei louvor na terra do meu cativeiro, porque manifestou a sua glória sobre uma nação pecadora.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 8, 'Convertei-vos, pois, ó pecadores, e sede justos diante de Deus, confiando em que ele usará convosco da sua misericórdia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 9, 'Quanto a mim, eu me regozijarei nele com toda a minha alma.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 10, 'Bendizei ao Senhor, vós todos os seus escolhidos; celebrai dias de alegria e rendei-lhe louvores.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 11, 'Jerusalém, cidade de Deus, o Senhor te castigou por causa das obras das tuas mãos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 12, 'Dá graças ao Senhor pelos teus bens, bendiz o Deus dos séculos, para que restabeleça em ti o seu santuário, reconduza a ti todos os cativos, e tu te alegres por todos os séculos dos séculos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 13, 'Tu brilharás com uma refulgente luz, e todos os povos da terra se prostrarão diante de ti.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 14, 'As nações virão a ti de longe, e, trazendo dádivas, adorarão em teus muros o Senhor, e terão a tua terra por santa.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 15, 'Eles invocarão o grande nome (do Senhor) dentro de ti.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 16, 'Serão malditos os que te desprezarem, condenados os que blasfemarem contra ti, benditos os que te edificarem.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 17, 'Tu alegrar-te-ás nos teus filhos, porque serão todos benditos, e se reunirão ao Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 18, 'Bem-aventurados todos os que te amam e se alegram na tua paz.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 19, 'Ó minha alma, bendiz ao Senhor, porque livrou a sua cidade de Jerusalém de todas as suas tribulações, ele, o Senhor nosso Deus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 20, 'Ditoso de mim, se restar ainda alguém da minha descendência, para ver o esplendor de Jerusalém.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 21, 'As portas de Jerusalém serão construídas de safiras e de esmeraldas, e de pedras preciosas todo o circuito dos seus muros.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 22, 'Todas as suas praças serão calçadas de pedras de brancura imaculada; em todas as suas ruas se cantará: Aleluia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 23, 'Bendito o Senhor, que a exaltou; que o seu reinado seja sobre ela pelos séculos dos séculos. Amen.');

-- Capítulo 14
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 14, 17);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 1, 'Assim terminaram as palavras de Tobias. Depois que recobrou a vista, viveu Tobias quarenta e dois anos, e viu os filhos de seus netos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 2, 'Tendo completado cento e dois anos, foi sepultado bonorificamenté em Ninive.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 3, 'Aos cinquenta e seis anos perdeu vista, e recobrou-a aos sessenta.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 4, 'O restante da sua vida passou-o na alegria; à medida que progredia no temor de Deus, aumentava a sua paz.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 5, 'A’ hora da morte, chamou à sua presença Tobias, seu filho, e sete jovens filhos deste, seus netos, e disse-Ihes:'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 6, 'A ruína de Ninive está próxima, porque a palavra do Senhor não falta; os nossos irmãos, que foram dispersos para longe da terra de Israel, voltarão para ela.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 7, 'Todo o seu país deserto será repovoado, e a casa de Deus, que ali foi queimada, será reedíficada. Para ela voltarão todos os que temem a Deus,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 8, 'e os gentios abandonarão os seus idolos, virão a Jerusalém, habitarão nela,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 9, 'e nela se alegrarão todos os reis da terra, apresentando as suas homenagens ao (Messias) rei de Israel.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 10, 'Ouvi, pois, meus filhos, o vosso pai; servi ao Senhor em verdade e trabalhai por fazerdes o que for do seu agrado ;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 11, 'recomendai a vossos filhos que façam obras de justiça e dêem esmolas, que se lembrem de Deus e que o bendigam em todo o tempo, em verdade, e com todas as suas forças.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 12, 'Ouvi-me, agora, meus filhos: não fiqueis aqui; mas no dia era que tiverdes sepultado vossa mãe, junto a mim em um mesmo sepulcro, desde logo dirigi vossos passos para sairdes daqui,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 13, 'porque eu vejo que a iniquidade desta cidade a levará à ruína.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 14, 'Tobias, depois da morte de sua mãe, saiu de Ninive com sua mulher e filhos, e os filhos de seus filhos, e voltou para casa de seus sogros.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 15, 'Encontrou-os ainda com saúde numa ditosa velhice; tomou cuidado deles, e ele mesmo lhes fechou os seus olhos. Tomou posse de toda a herança da casa de Raquel, viu os filhos de seus filhos até à quinta geração .'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 16, 'Tendo vivido noventa e nove anos no temor do Senhor, sepultaram-no com alegria.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 17, 'Toda a sua parentela e toda a sua descendência perseveraram numa numa vida íntegra e num santo procedimento, modo que foram amados tanto por Deus como pelos homens e por todos os habitantes do país.');

