-- undefined (undefined)

-- Capítulo 1
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 1, 11);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 1, 'Palavra do Senhor, que foi dirigida a Oseias, filho de Beeri, nos dias de Osias, de Joatan, de Acaz, de Ezequias, reis de Judá, e nos dias de Jeroboão, filho de Joás, rei de Israel.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 2, 'Começou o Senhor a falar a Oseias, quando lhe disse: Vai, toma por mulher uma prostituta e tem filhos de prostituição, porque a terra (de Israel) não cessa de se prostituir (ou idolatrar), abandonando o Senhor.1'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 3, '(Oseias) foi e tomou por sua mulher a Gomer, filha de Deblaim, a qual concebeu e lhe deu à luz um filho.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 4, 'O Senhor disse a Oseias: Põe-lhe o nome de Jezrael, porque dentro de pouco tempo eu tirarei vingança da casa de Jeú, pelo sangue (que derramou na cidade) de Jezrael, e porei fim à realeza da casa de Israel.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 5, 'Naquele dia quebrarei o arco (ou poder militar) de Israel no vale de Jezrael.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 6, 'Ela concebeu outra vez e deu à luz uma filha. O Senhor disse a Oseias: Põe-lhe o nome de Sem-misericórdla (ou: Aquela de que se não tem pena) — porque não me tornarei mais a compadecer da casa de Israel, antes a esquecerei inteiramente.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 7, 'Compadecer-me-ei, porém, da casa de Judá; salvá-los-ei por meio do Senhor seu Deus, e não pelo arco, nem pela espada, nem pela guerra, nem pelos cavalos, nem pelos cavaleiros.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 8, '(Gomer) desquitou a sua filha, chamada Sem-misericórdia, concebeu outra vez e deu à luz um filho.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 9, 'O Senhor disse a Oseias: Põe-lhe o nome de Não-meu-povo, porque vós já não sois meu povo, e eu não sou mais vosso (Deus).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 10, 'Porém (um dia) o número dos filhos de Israel será como a areia do mar, que não se pode medir nem contar. E acontecerá que no lugar onde se lhes disse: Vós não sois já meu povo — se lhes dirá: Vós sois filhos do Deus vivo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 11, 'Então os filhos de Judá e os filhos de Israel se juntarão, constituirão sobre si um só chefe, e transbordarão para fora do seu território, porque grande será o dia de Jezrael. (ver nota)');

-- Capítulo 2
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 2, 24);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 1, 'Dizei a vossos irmãos: Vós sois o meu povo; — e a vossa irmã: Tu alcançaste misericórdia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 2, 'Levai a juízo a vossa mãe, levai-a a juízo, porque ela não é mais minha esposa, nem eu seu esposo. Tire ela as suas fornicações da sua face, e os seus adultérios do meio de seus seios,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 3, 'para que não suceda que eu a despoje, ficando ela nua, que a ponha no estado em que se encontrava no dia do seu nascimento, que a torne semelhante a um deserto, a transforme numa terra ressequida e a mate à sede.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 4, 'Não me compadecerei dos seus filhos, porque são filhos da prostituição.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 5, 'Com efeito, sua mãe prostituiu-se (idolatrando), aquela que os concebeu conduziu-se mal e disse: Irei após os meus amantes (ou ídolos), que me dão o meu pão e a minha água, a minha lã e o meu linho, o meu azeite e a minha bebida.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 6, 'Por isso vou fechar-lhe o caminho com uma sebe de espinhos; cercá-lo-ei com um muro, e ela não encontrará as suas veredas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 7, 'Irá em seguimento dos (ídolos) seus amantes, mas não os alcançará; buscá-los, mas não os encontrará. Dirá então: Irei e voltarei para o meu primeiro (legítimo) esposo, porque então eu era mais feliz do que agora.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 8, 'Ela não reconheceu que fui eu (e não os ídolos) que lhe dei o trigo, o vinho e o azeite, e que lhe prodigalizei a prata e o ouro, que, ofereceram a Baal.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 9, 'Por isso (mudarei agora de proceder a seu respeito), ou tomarei o meu trigo a seu tempo, e o meu vinho na estação própria, e tirarei (das suas mãos) a minha lã e o meu linho, que cobrem a sua nudez.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 10, 'Agora descobrirei a sua vergonha aos olhos dos seus amantes (que em nada lhe podem valer), e ninguém a livrará da minha mão;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 11, 'farei cessar todos os seus divertimentos, as suas solenidades, as suas neoménias, os seus sábados e todas as suas festas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 12, 'Destruirei as suas vinhas e as suas figueiras, de que ela disse: Estas são as recompensas que me deram os meus amantes — e reduzi-la-ei a um matagal, e devorá-la-ão os animais selvagens.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 13, 'Castigá-la-ei pelos dias em que prestou culto aos Baais, (ou aos ídolos), queimando-lhes incenso, enquanto se enfeitava com as suas arrecadas e com os seus colares e ia após os seus amantes, esquecendo-se de mim, diz o Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 14, 'Por isso a atrairei, conduzi-la-ei à soledade e falar-lhe-ei ao coração. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 15, 'Dar-lhe-ei a suas vinhas e o vale de Acor, como porta de esperança; ali cantará (hinos a Deus) como nos dias da sua juventude, e como nos dias em que subiu da terra do Egipto.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 16, 'Nesse dia, diz o Senhor, ela me chamará: Meu esposo — ; não me chamará mais: Meu Baal (como aos seus ídolos).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 17, 'Tirarei da sua boca os nomes dos Baais, para que nunca mais sejam pronunciados os seus nomes.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 18, 'Farei aliança para eles naquele dia com os animais selvagens, com as aves do céu e com os répteis da terra; tirarei do país o arco, a espada e a guerra, e fá-los-ei repousar com toda a segurança.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 19, 'Então me desposarei contigo para sempre, desposar-me-ei contigo na justiça e no direito, na misericórdia e no amor;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 20, 'desposar-me-ei contigo com uma inviolável fidelidade, e saberás que eu sou o Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 21, 'Nesse dia atenderei, diz o Senhor, atenderei os céus, e eles atenderão a terra; (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 22, 'a terra atenderá o trigo, o mosto e o azeite, e estas coisas atenderão Jezrael.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 23, 'Farei dela, para mim, no país, um terreno de sementeira, compadecer-me-ei daquela (nação) que se chamava Sem-misericórdia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 24, 'Direi ao que se chamava Não-meu-povo: Tu és o meu povo. E ele me dirá: Tu és o meu Deus.');

-- Capítulo 3
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 3, 5);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 1, 'O Senhor disse-me: Vai, ainda, e ama uma mulher (que foi) amada dum amante e adúltera: é assim que o Senhor ama os filhos de Israel, ainda quando eles põem os olhos em deuses estranhos e gostam de tortas de uvas. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 2, 'Comprei a (tal) mulher por quinze ciclos de prata, e por homer e meio de cevada.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 3, 'E disse-lhe: Tu me esperarás largos dias, durante os quais não te portarás mal, não te entregarás a homem algum, e também eu esperarei por ti. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 4, 'Porque os filhos de Israel estarão durante muitos dias sem rei e sem chefe, sem sacrifício, sem esteia, sem éfode e sem terafins; (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 5, 'depois disto, os filhos de Israel voltarão a buscar o Senhor seu Deus, e (o descendente de) Davide, seu rei; e, no fim dos tempos, olharão com respeitoso temor para o Senhor e para os bens (que ele lhes terá feito).');

-- Capítulo 4
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 4, 19);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 1, 'Ouvi a palavra do Senhor, filhos de Israel, porque o Senhor vai entrar em juízo com os habitantes desta terra, visto que não há verdade, nem misericórdia, nem conhecimentos de Deus nesta terra.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 2, 'O perjúrio, a mentira, o homicídio, o furto e o adultério inundaram tudo, e derrama-se sangue sobre sangue.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 3, 'Por isso a terra está de luto; e todo o que nela habita definha: os próprios animais selvagens, as aves do céu e até os peixes do mar perecem.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 4, 'Todavia ninguém se ponha a corrigir ou a repreender pessoa alguma. É contra ti, sacerdote, que vão as minhas censuras.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 5, 'Por isso tropeçarás em pleno dia, e tropeçará também contigo o (falso) profeta. De noite farei perecer tua mãe, (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 6, 'O meu povo perece, por falta de conhecimento. Porque tu (ó sacerdote) rejeitaste a ciência (que, por dever de estado, havia de possuir), também eu excluirei do exercício do meu sacerdócio; visto que esqueceste da lei do teu Deus, também eu me esquecerei de teus filhos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 7, 'Quanto mais se multiplicaram, mais pecaram contra mim; mudaram a sua glória em ignomínia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 8, 'Nutrem-se dos pecados do meu povo, desejam ardentemente as suas iniquidades.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 9, 'Portanto o sacerdote será (tratado) como o povo; castigá-lo-ei pelos seus (maus) caminhos, dar-lhe-ei segundo as suas obras.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 10, 'Comerão, e não ficarão saciados; prostituir-se-ão e não se multiplicarão, porque abandonaram o Senhor obstinadamente.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 11, 'A fornicação, o vinho e o mosto fazem perder o sentido.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 12, 'O meu povo consulta um pedaço de pau, e o seu bordão lhe faz revelações, porque o espírito da fornicação (ou a idolatria) os enganou, e eles prostituiram-se, deixando o seu Deus. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 13, 'Oferecem sacrifícios sobre os cumes dos montes e queimam oferendas sobre os outeiros, debaixo dos carvalhos, dos choupos e dos terebintos, de sombra amena. Por isso as vossas filhas se prostituem, e as vossas noras são adúlteras.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 14, 'Não castigarei as vossas filhas, quando se prostituírem, nem as vossas noras, quando adulterarem, porque eles mesmos (os pais e esposos) têm trato com as meretrizes e sacrificam com pessoas devassas. O povo (insensato e) sem entendimento será castigado. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 15, 'Se tu, é Israel, te entregas à prostituição (à idolatria), ao menos não peque Judá; não vades a Gálgala, não subais a Betaven (para idolatrar) e não jureis dizendo: Vive o Senhor. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 16, 'Porque Israel rebelou-se como uma vaca indomável; agora o apascentará o Senhor como a um cordeiro numa espaçosa campina.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 17, 'Efraim (ou Israel) está ligado aos ídolos: deixa-o (ó Judá).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 18, 'Depois de se entregarem à bebida, entregam-se à fornicação (ou idolatria); os seus chefes comprazem-se na ignomínia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 19, 'O vento (da cólera divina) levá-los-á nas suas asas, e eles serão confundidos por causa dos seus sacrifícios.');

-- Capítulo 5
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 5, 15);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 1, 'Ouvi isto, ó sacerdotes! Casa de Israel, ouve com atenção! Escuta, ó casa real! É sobre vós que se vai exercer o juízo, pois tendes sido um laço para a sentinela (do povo), uma rede estendida (ou armadilha) sobre o Tabor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 2, 'Os perseguidores levaram ao extremo a maldade, mas eu darei a todos o castigo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 3, 'Conheço Efraim, e Israel não me é encoberto. Efraim prostituiu-se, Israel contaminou-se.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 4, 'Não aplicam os seus trabalhos a voltar para o seu Deus, porque o espírito de prostituição (ou idolatria) está no meio deles, porque não conhecem o Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 5, 'A arrogância de Israel vê-se no seu rosto, Israel e Efraim tropeçarão por causa da sua iniquidade, e Judá também cairá com eles.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 6, 'Irão buscar o Senhor com as suas ovelhas e os seus bois, e não o encontrarão: retirou-se deles.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 7, 'Atraiçoaram o Senhor, porque geraram filhos bastardos; agora serão consumidos dentro dum mês, eles e tudo o que possuem. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 8, 'Tocai a buzina em Gabaa, (tocai) a trombeta em Rama; levantai gritos em Betaven! Acautela-te, Benjamim !'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 9, 'Efraim será desolado no dia do castigo. Sobre as tribos de Israel anuncio uma coisa certa.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 10, 'Os príncipes de Judá procederam como aqueles que mudam os marcos (e roubam a terra dos vizinhos); derramarei sobre eles a minha ira como uma torrente.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 11, 'Efraim vê-se tiranizado e oprimido em juízo, porque quis ir após os ídolos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 12, 'Serei para Efraim como a traça (que tudo destrói), e para a casa de Judá como a podridão.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 13, 'Efraim viu a sua fraqueza, e Judá a sua chaga; Efraim recorreu a Assur, e (Judá) buscou um grande rei, mas ele não poderá curar-vos, não poderá sarar a vossa chaga.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 14, 'Serei para Efraim como um leão, para a casa de Judá como um leãozinho; eu, eu mesmo despedaçarei a presa e ir-me-ei com ela, levá-la-ei, e ninguém ma arrancará.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 15, 'Irei e voltarei para a minha habitação até que reconheçam o seu pecado e busquem a minha face. (ver nota)');

-- Capítulo 6
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 6, 11);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 1, 'Eles, vendo-se na sua angústia, recorrerão a mim. Vinde (dirão), voltemos para o Senhor,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 2, 'porque (assim, como) nos dilacerou, (também) nos sarará; ele nos feriu, ele nos curará.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 3, 'Dar-nos-á novamente a vida em dois dias; ao terceiro dia levantar-nos-á, e viveremos na sua presença. Entraremos na ciência do Senhor, segui-lo-emos a fim de o conhecer. A sua vinda está preparada como a da aurora, e ele descerá sobre nós como a chuva, como a chuva da primavera que costuma vir sobre a terra.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 4, 'Que te farei, Efraim? Que te farei, Judá? A vossa caridade é como uma nuvem da manhã, como o orvalho transitório da manhã.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 5, 'Por isso é que os tratei duramente pelos profetas, que os matei pelas palavras da minha boca; os juízos proferidos contra ti, são como a luz que se levanta.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 6, 'Porque o que eu quero é o amor, e não os sacrifícios, o conhecimento de Deus mais que os holocaustos. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 7, 'Mas eles, como homens (inconstantes), violaram a aliança (que tinham feito comigo), atraiçoaram-me.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 8, 'Galaad é (agora) uma cidade de malfeitores, toda inundada de sangue.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 9, 'Como bandidos que assaltam viandantes, assim os sacerdotes no caminho de Siquém assassinam e cometem crimes.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 10, 'Vi na casa de Israel coisas horríveis; ali se acham as prostituições de Efraim, ali se manchou Israel.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 11, 'Mas para ti também, ó Judá, está preparada uma ceifa (de castigos), quando eu restaurar o meu povo.');

-- Capítulo 7
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 7, 16);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 1, 'Quando eu tratava de curar Israel, tornou-se patente a iniquidade de Efraim e a malícia de Samaria, pois praticam a mentira. O ladrão entra nas casas, e por fora anda o salteador.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 2, 'Não dizem nos seus corações que me lembro de toda a sua malícia: actualmente cercam-nos as suas impiedades, que estão a descoberto diante da minha face.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 3, 'Com a sua malícia alegram o rei, e os príncipes com as suas mentiras.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 4, 'São todos uns adúlteros, semelhantes a um forno aceso pelo forneiro, que cessa de o aquecer mais, depois de ter trabalhado a massa até se levedar. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 5, 'No dia do nosso rei, os príncipes aqueceram-se com o calor do vinho, enquanto ele estendia a sua mão aos bobos. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 6, 'O seu interior é como um forno, os seus corações, uma emboscada. Toda a noite dormiu o padeiro; pela manhã o forno estava todo esbraseado como um fogo ardente. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 7, 'Todos eles estão quentes como um forno e devoram os seus juízes. Todos os seus reis caíram; não há entre eles quem levante a voz para mim.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 8, 'Efraim mistura-se com os povos (idólatras); Efraim tornou-se como um bolo que não se volta. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 9, 'Os estrangeiros devoraram a sua força, sem ele o sentir; os seus cabelos tornaram-se brancos, sem ele o perceber. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 10, 'A soberba de Israel transparece-lhe no rosto; não se voltam para o Senhor seu Deus, não o buscam apesar de tudo isto.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 11, 'Efraim tornou-se como uma pomba imbecil, som inteligência. Chamam o Egipto, vão ter com os Assírios.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 12, 'Depois que tiverem ido, estenderei sobre eles a minha rede, e fá-los-ei cair como aves do céu; castigá-los-ei segundo foi dito mas suas assembleias. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 13, 'Ai deles, porque se retiraram de mim! Serão destruídos, porque prevaricaram contra mim! Enquanto os queria salvar, proferiam mentiras contra mim.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 14, 'Não clamam a mim do fundo do seu coração, mas uivam (desesperados) nos seus leitos! Somente temem pelo trigo e pelo vinho, revoltam-se contra mim.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 15, 'Instruí-os e dei vigor aos seus braços, mas eles meditaram o mal contra mim.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 16, 'Voltam-se, mas não para o alto; são como um arco doloso; cairão mortos á espada os seus príncipes, por causa do furor (ou insolência) da sua língua. Isso fará com que riam deles na terra do Egipto. (ver nota)');

-- Capítulo 8
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 8, 14);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 1, 'Emboca a trombeta! (Anuncia que o inimigo) como uma águia, se precipita sobre a casa do Senhor, porque transgrediram a minha aliança e violaram a minha lei.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 2, 'Clamam a mim, dizendo; Meu Deus, nós, o povo de Israel, te conhecemos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 3, 'Israel rejeitou o bem; o inimigo o persegue.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 4, 'Estabeleceram reis, mas não da minha parte, estabeleceram chefes, mas eu não os conheço; fabricaram para si ídolos da sua prata e do seu ouro, para sua perdição.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 5, 'O teu bezerro (que adoravas), ó Samaria, é repelido por mim. O meu furor acendeu-se contra eles. Até quando se não poderão eles purificar (da sua idolatria)?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 6, 'Porque de Israel é que veio este novilho; um artífice o fabricou, ele não é Deus; o bezerro de Samaria será despedaçado!'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 7, 'Visto que semearam ventos, colherão tempestades; não há ali uma espiga, o seu grão não dará farinha; se desse alguma, come-la-iam os estrangeiros. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 8, 'Israel está devorado; é tratado entre as nações como coisa que não presta.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 9, 'Porque recorreram a Assur, que é como um asno silvestre, que anda só. Efraim deu presentes aos seus amantes (os Assírios).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 10, 'Mas, ainda que ofereçam presentes às nações, eu os juntarei na (Assíria), e eles (estando cativos) serão ainda algum tempo sujeitos ao fardo do rei e dos príncipes.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 11, 'Efraim multiplicou os altares de pecado; esses altares só lhe serviram para pecar.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 12, 'Escrevi para ele as palavras da minha lei, mas ele considera-a como lei alheia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 13, 'Oferecem vítimas e comem-lhes a carne, mas o Senhor mão as aceita. Agora lembrar-se-á da sua iniquidade, castigará os seus pecados. Hão-de voltar para o Egipto.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 14, 'Israel esqueceu-se do seu Criador e edificou palácios; Judá multiplicou as suas cidades fortificadas; mas enviarei fogo sobre as suas cidades, e ele devorará (todos) os seus edifícios.');

-- Capítulo 9
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 9, 17);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 1, 'Não te alegres, Israel, não exultes como os povos (pagãos), porque te prostituiste, sendo infiel ao teu Deus, amaste a recompensa impura, por sobre todas as eiras de trigo. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 2, 'A eira e o lagar não os sustentarão, e o vinho iludirá a sua espectativa.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 3, 'Não habitarão na terra do Senhor. Os de Efraim voltarão para o Egipto, e comerão alimentos impuros entre os Assírios.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 4, 'Não farão libações de vinho ao Senhor, nem lhe oferecerão agradáveis sacrifícios; o seu pão será como o pão que se come no luto: todos os que comerem dele; ficarão impuros; o seu pão será só para eles, não entrará na casa do Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 5, 'Que fareis vós no dia solene, no dia da festa do Senhor?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 6, 'Eles partem por causa da devastação (da sua terra). O Egipto os recolherá, Menfis os sepultará; as suas preciosidades de prata serão das urtigas e, crescerão os abrolhos nas suas casas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 7, 'Chegaram os dias do castigo, chegaram os dias da retribuição. Clama Israel: O profeta é louco, o varão espiritual é insensato! À enormidade da tua iniquidade junta-se a da tua perseguição.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 8, 'A sentinela de Efraim — com o meu Deus — o profeta, encontra um laço de caçador sobre todos os seus caminhos, a perseguição (mesmo) na casa do seu Deus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 9, 'Estão profundamente corrompidos, como nos dias de Gabaa. O Senhor se lembrará da sua iniquidade e castigará os seus pecados. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 10, 'Encontrei Israel como cachos de uvas no deserto; vi os vossos pais como os primeiros frutos da figueira. Porém, chegados a Beelfegor, consagraram-se à infâmia e tornaram-se abomináveis como as coisas que amaram.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 11, 'A glória de Efraim voará como uma ave; não haverá nascimento, nem gravidez nem concepção.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 12, 'Mas, ainda mesmo que criassem alguns filhos, eu faria com que ficassem sem eles, para não restar ninguém. E ai deles quando eu os abandonar!'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 13, 'Efraim, pelo que vi, era como Tiro, apoiada na sua beleza; mas Efraim levará seus filhos ao que lhes há-de tirar a vida.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 14, 'Dá-lhes, Senhor... Porém, que lhes darás? Dá-lhes um ventre estéril e peitos secos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 15, 'Toda a sua malícia (apareceu) em Gálgala; foi lá que lhes concebi aversão; lançá-los-ei fora da minha casa, por causa da malícia das suas obras; não tornarei mais a ter-lhes amor; todos os seus príncipes são uns rebeldes.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 16, 'Efraim está ferido (de morte), a sua raiz seca: (os de Efraim) não darão mais fruto. Se, porém, tiverem filhos, matarei os queridos de suas entranhas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 17, 'O meu Deus os rejeitará, porque não o ouviram; andarão errantes entre as nações.');

-- Capítulo 10
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 10, 15);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 1, 'Israel era uma vinha frondosa, que dava os frutos correspondentes. Quanto mais abundou em frutos, tanto mais multiplicou os seus altares; quanto mais rica era a terra, mais ricas estelas construía.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 2, 'É falso o seu coração: vão sofrer o castigo devido. Ele mesmo (o Senhor) quebrará os seus altares e deitará abaixo as suas estelas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 3, 'Dentro em breve eles dirão: Nós não temos rei (que possa salvarmos), porque não tememos o Senhor; e que faria por nós o rei (querendo Deus castigarmos)?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 4, 'Proferem palavras vãs, juram falso, concluem alianças, mas o castigo de (Deus) brotará como erva venenosa sobre os sulcos dum campo (semeado).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 5, 'Os habitantes da Samaria tremerão por causa do bezerro, (de ouro) de Betaven. O seu povo (que adorava este ídolo) toma luto por ele, e o bando dos seus sacerdotes faz lamentações por causa de a sua riqueza ter sido transferida para longe dele.1'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 6, 'Ele também será levado para a Assíria, como um presente ao grande rei. A confusão apoderar-se-á de Efraim e Israel ficará envergonhado por ter seguido os seus caprichos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 7, 'A Samaria está aniquilada. O seu rei é como espuma sobre a superfície da água.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 8, 'Os lugares altos de Betaven, que fazem o pecado de Israel, serão destruídos; sobre os seus altares crescerão espinhos e abrolhos. Então dirão às montanhas : Cobri-nos! — e aos outeiros: Caí sobre nós. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 9, 'Desde os dias de Gabaa, tens pecado, ó Israel. Aí tomaram posições (contra mim). Não os apanhará em Gabaa a guerra (declarada) contra os filhos da iniquidade? (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 10, 'Castigá-los-ei à medida do meu desejo; porque devem ser punidos por causa das suas duas iniquidades, juntar-se-ão contra eles os povos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 11, 'Efraim era como uma novilha bem tratada, que gostava de pisar a eira (na ocasião da debulha); mas eu porei um jugo sobre o seu pescoço; atrelarei Efraim, Judá lavrará, Jacob puxará a grade, (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 12, 'Semeai para vós na justiça, segai segundo a misericórdia, rompei os vossos pousios, porque é tempo de buscar o Senhor, até que venha ensinar-vos a justiça _(ou santidade). (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 13, 'Cultivastes a impiedade, segastes a iniquidade, comestes o fruto da mentira. Confiaste nos teus caminhos e na multidão dos teus valentes.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 14, 'Levantar-se-á tumulto entre o teu povo; todas as tuas fortificações serão destruídas, como Salmana destruiu Bet-Arbel, no dia da peleja, em que a mãe foi esmagada sobre os filhos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 15, 'Eis o que vos fez Betel, por causa da enormidade das vossas iniquidades.');

-- Capítulo 11
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 11, 13);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 1, 'Desde a aurora, será completamente destruído o rei de Israel. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 1, 'Quando Israel era menino, eu o amei, e chamei do Egipto o meu filho.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 2, 'Mas, quanto mais os meus profetas os chamaram, tanto mais eles se retiraram da sua presença; sacrificaram aos Baais e queimaram oferendas aos ídolos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 3, 'Entretanto eu ensinava (os de) Efraim a andar, trazia-os nos meus braços, mas eles não reconheceram que era eu quem cuidava deles.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 4, 'Segurava-os com laços humanos, com laços de amor; fui para eles como o que tira o jugo de cima do pescoço e aproximei-me deles para os nutrir.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 5, '(Israel) não voltará para a terra do Egipto, mas o Assírio será seu rei, porquanto não quiseram converter-se.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 6, 'A espada fará devastações nas suas cidades, consumirá os seus escolhidos, devorá-los-á por causa dos seus maus desígnios.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 7, 'O meu povo é inclinado a afastar-se de mim; quando se convida a subir ao que está no alto, ninguém procura elevar-se.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 8, 'Como te tratarei, ó Efraim? Entregar-te-ei, ó Israel? Poderei tratar-te como a Adama, ou tornar-te como Seboim (depois de te ter amado tanto) ? O meu coração dá voltas dentro de mim mesmo, comove-se a minha compaixão.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 9, 'Não desafogarei o furor da minha ira, não destruirei mais Efraim, porque sou Deus e não um homem; sou o Santo no meio de ti, não gosto de destruir.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 10, 'Eles seguirão o Senhor que rugirá como um leão; quando ele rugir, os filhos do ocidente tremerão. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 11, 'Voarão do Egipto como uma ave, e da terra dos Assírios como uma pomba, e estabelecê-los-ei em suas casas diz o Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 12, 'Efraim cercou-me de mentira, e a casa de Israel, de engano; Judá, porém, conduziu-se com Deus e com os santos como uma testemunha fiel.');

-- Capítulo 12
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 12, 14);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 1, 'Efraim apascenta-se de vento, vai atrás do vento do oriente. Todos os dias multiplica a mentira e a violência; faz aliança com os Assírios e leva o seu (excelente) azeite ao Egipto.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 2, 'O Senhor virá, pois, a juízo com Judá; castigará Jacob pelo seu proceder, dar-lhe-á o pago que merecem as suas obras.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 3, 'Jacob suplantou seu irmão no ventre de sua mãe, e com a sua fortaleza lutou com Deus; (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 4, 'lutou com o anjo e ficou vencedor, chorou e suplicou-lhe; encontrou-o em Betel, onde (o Senhor) falou connosco,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 5, 'ele, o Senhor Deus dos exércitos, cujo nome é Iavé.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 6, 'Converte-te pois, ao teu Deus; guarda a misericórdia e a justiça, e espera sempre no teu Deus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 7, 'Canaan, que tem na mão uma balança enganosa, ama a fraude. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 8, 'Efraim disse; Em verdade tornei-me rico, adquiri fortuna; em todos os meus ganhos, não se encontrará que eu tenha cometido injustiça alguma.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 9, 'Eu, que sou o Senhor teu Deus, desde a terra do Egipto, far-te-ei repousar ainda nas tuas tendas, (apesar da tua obstinação), como nos dias da festa (dos Tabernáculos).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 10, 'Também falei aos profetas e multipliquei as visões; por meio dos mesmos profetas apresentei-vos parábolas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 11, 'Se os galaaditas são ímpios, serão reduzidos a nada, em Galgala, onde imolam touros; além disso os seus altares se transformarão em montões de escombros sobre os sulcos dos campos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 12, 'Jacob fugiu para a planície de Aram, Israel serviu (a Labão) para adquirir uma esposa, para adquirir uma mulher guardou o gado. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 13, 'O Senhor fez sair Israel do Egipto por meio dum profeta, e por melo dum profeta o povo foi guardado.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 14, '(Não obstante) Efraim provocou a ira (divina) mas o sangue que derramou recairá sobre ele, e o seu Senhor lhe dará (a paga) do seu ultraje.');

-- Capítulo 13
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 13, 15);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 1, 'Quando Efraim, terrível pelas suas palavras, se tornava forte em Israel, delinquiu, adorando Baal e morreu.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 2, 'Agora continuam a pecar; fizeram para si com sua prata, estátuas fundidas, ídolos de sua invenção, o que tudo é obra de artistas. A estes (ídolos) é que se dirigem, oferecem-lhes sacrifícios humanos, e dão beijos nos bezerros.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 3, 'Por isso serão como a nuvem da manhã, como o orvalho matinal, que logo passa, como o pó arrebatado da eira pelo torvelinho, como o fumo que sai pela janela.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 4, 'Todavia eu sou o Senhor teu Deus desde (que saiste da) terra do Egipto; tu não conhecerás outro Deus fora de mim; não há Salvador senão eu.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 5, 'Conheci-te (tratando-te como filho) no deserto, numa terra estéril.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 6, 'Eles fartaram-se quando tiveram a sua pastagem; uma vez saciados, levantaram o seu coração e esqueceram-se de mim.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 7, 'Serei para eles como um leão, como uma pantera no caminho, a espreitar.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 8, 'Sair-lhes-ei ao encontro como uma ursa a quem roubaram os seus cachorros, dilacerarei o seu coração, como um leão os devorarei, e despedaçá-los-ei como uma fera do campo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 9, 'Estás perdido, Ó Israel, só em mim está o teu auxílio.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 10, 'Onde está o teu rei para te salvar em todas as tuas cidades? Onde os teus juízes de quem (me) disseste: Dá-me um rei e príncipes (que me governem)?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 11, 'Dei-te um rei no meu furor, e retiro-to na minha indignação.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 12, 'As iniquidades de Efraim, estão atadas juntas, o seu pecado está posto em reserva.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 13, 'Sobre ele virão as dores, como de uma mulher que está de parto; seu filho é insensato, o qual, na hora devida, não se põe em termos de sair do seio materno.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 14, '(Não obstante) livrá-los-ei do poder do sepulcro, resgatá-los-ei da morte? Ó morte, onde está o teu flagelo? ó inferno, onde a tua destruição? O arrependimento está escondido a meus olhos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 15, 'Entretanto que (Efraim) frutificar entre seus irmãos, virá o vento do oriente, o vento do Senhor, que se levanta do deserto, o qual secará a sua nascente, estancará a sua fonte, roubará o tesouro de todos os objectos preciosos.');

-- Capítulo 14
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 14, 10);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 1, 'A Samaria será castigada, porque se revoltou contra o seu Deus. (Os sem habitantes) cairão ao fio da espada, serão esmagados os seus meninos, e abertos os ventres das mulheres grávidas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 2, 'Converte-te, ó Israel, ao Senhor teu Deus, porque pela iniquidade é que caiste.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 3, 'Tomai convosco palavras (de arrependimento), convertei-vos ao Senhor, dizei-lhe; Tira-nos todas as nossas iniquidades, aceita este bem (ou bom desejo que temos); queremos oferecer-te, como sacrifício, os louvores dos nossos lábios.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 4, 'Assur não nos salvará (mas sim tu Senhor); não montaremos (arrogantes) em cavalos e nunca mais chamaremos Deus à obra das nossas mãos. (Fazemos esta súplica) porque em ti o órfão encontra compaixão,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 5, 'Curarei a sua infidelidade (responde o Senhor), amá-los-ei espontâneamente, porque já o meu furor se afastou deles.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 6, 'Serei como o orvalho para Israel; crescerá como um lírio, e deitará raízes como o Líbano.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 7, 'Estender-se-ão os seus ramos, a sua glória será como a da oliveira, o seu perfume como o do Líbano.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 8, 'Virão repousar debaixo da sua sombra; viverão de trigo e propagar-se-ão como a vinha; a sua nomeada será como a do vinho do Líbano.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 9, '(Depois disto) que terá Efraim de comum com os ídolos? Fui eu que o afligi e que o tornei feliz ; sou como um cipreste sempre verdejante; em mim terão origem os teus frutos (ó Israel).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 10, 'Quem é o sábio que compreenderá estas coisas (que escrevi)? Quem tem inteligência para as conhecer? Porque os caminhos do Senhor são rectos; por eles andarão os justos, mas neles cairão os prevaricadores. (ver nota)');

