-- undefined (undefined)

-- Capítulo 1
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 1, 21);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 1, 'Visão de Abdias. Isto diz o Senhor Deus a Edom; Eis o que ouvimos do Senhor, que um mensageiro foi enviado a dizer às nações: Levantai-vos e partamos todos contra Edom, para o combater.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 2, 'Tu vês (diz o Senhor a Edom) que te fiz pequenino entre as nações; és desprezível em extremo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 3, 'A soberba do teu coração transviou-te, a ti que habitas nas fendas dos rochedos, que fazes das alturas a tua morada, que dizes dentro do teu coração: Quem me fará cair por terra?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 4, 'Ainda que te eleves, como a águia, e ponhas o teu ninho entre os astros, precipitar-te-ei de lá, diz o Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 5, 'Se ladrões entrassem em tua casa ou salteadores de noite, não se teriam contentado com roubar o preciso (deixando o resto)? Se viessem a ti vindimadores (à tua vinha), não deixariam nada de rebusco?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 6, 'Como esquadrinharam a Esaú (ou os Idumeus), investigaram os seus esconderijos!'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 7, 'Expulsaram-te até à fronteira; todos os teus aliados zombaram de ti; os (que se diziam) teus amigos subjugaram-te; os que comiam o teu pão, armaram-te laços à falsa fé. Edom não tem inteligência!'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 8, 'Acaso naquele dia não farei desaparecer os sábios da Idumeia, diz o Senhor, e a inteligência do monte de Esaú?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 9, 'Os teus valentes, ó Teman, serão tomados de medo, de maneira que morrerá todo o varão sobre o monte de Esaú.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 10, 'Por causa da mortandade, da violência que cometeste contra e teu irmão Jacob, cobrir-te-á a confusão, e perecerás para sempre.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 11, 'No dia em que, diante de ti (sem te importares com isso), bárbaros faziam prisioneiro o seu exército, em que estrangeiros entravam pelas suas portas e deitavam sortes sobre Jerusalém, tu também eras como um deles.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 12, 'Não te deleites contemplando teu irmão, no dia do seu infortúnio; não te alegres sobre os filhos de Judá no dia da sua perdição; não te portes com insolência no dia da angústia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 13, 'Não entres pelas portas (ou cidades) do meu povo no dia da sua ruína (para recolher despojos); não te alegres com os seus males no dia da sua desgraça; não deites a mão às suas riquezas, no dia da sua calamidade;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 14, 'não te ponhas nas encruzilhadas para matar os (Hebreus) que fugirem; não entregues os restos dos seus habitantes no dia da tribulação.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 15, 'Porque o dia (do castigo) do Senhor está perto para todas as nações, far-se-á contigo como tu fizeste (com o meu povo): (Deus) fará cair sobre a tua cabeça as tuas obras.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 16, 'Assim como vós bebestes (sacrilegamente) sobre o meu santo monte, assim também beberão de continuo (do cálice da cólera divina) todas as (outras) nações (idólatras); beberão, sorverão, e virão a ser como se nunca tivessem sido.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 17, 'Mas sobre o monte de Sião haverá escapados, será (um lugar) santo e a casa de Jacob despojará aqueles que a despojaram.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 18, 'A casa de Jacob será um fogo, a casa de José uma chama, e a casa de Esaú palha seca, a qual será abrasada e devorada por aquelas, sem ficar resto algum da casa de Esaú, porque o Senhor assim o disse.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 19, 'Os que habitam ao meio-dia ocuparão o monte (ou pais) de Esaú, e os que habitam na planície (tomarão) o país dos Filisteus; serão senhores do país de Efraim e do território de Samaria, e Benjamim possuirá Galaad.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 20, 'Os dispersos (até então) do exército dos filhos de Israel ocuparão todas as terras dos Cananeus até Sarepta, e os deportados de Jerusalém, que estão em Sefarad, possuirão as cidades do meio-dia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 21, 'Subirão salvadores ao monte de Sião para julgar o monte de Esaú, e o império pertencerá ao Senhor.');

