-- undefined (undefined)

-- Capítulo 1
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 1, 17);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 1, 'Oráculo revelado a Habacuc, profeta,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 2, 'Até quando, Senhor, clamarei sem que me ouças? Até quando levantarei a minha voz pará ti, padecendo violência, sem que me salves?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 3, 'Por que me mostras iniquidades, e contemplas, indiferente, a aflição. Se se decide uma causa em juízo, a contradição é que prevalece.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 4, 'Por esta causa é quebrantada a lei, e a justiça não chega a triunfar, porque o ímpio prevalece contra o justo, ó o direito sai falseado.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 5, 'Ponde os olhos nas nações (diz o Senhor) e vede; admirai-vos e pasmai, porque vou fazer uma coisa em vossos dias, que não acreditaríeis se vo-la contassem,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 6, 'Vou suscitar os Caldeus, esse povo cruel e impetuoso, que percorre a superfície da terra, para se apoderar das moradas que não são suas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 7, 'E horrível e tremendo, autor do seu direito e da sua grandeza.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 8, 'Os seus cavalos são mais ligeiros que leopardos, mais velozes que lobos durante a noite; a sua cavalaria precipita-se (ao ataque), os seus cavaleiros vêm de longe, voam como a águia que se arroja sobre a presa.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 9, 'Acorrem todos à pilhagem; o seu rosto é como um vento abrasador; amontoam cativos como areia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 10, 'Ele (o Caldeu) troça dos reis, ri-se dos príncipes, zomba de todas as fortalezas: levanta montões de terra (contra elas) e toma-as.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 11, 'Depois o furacão muda de sentido e passa, comete o mal, ele cujo deus é a força.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 12, 'Porém não és tu, Senhor, desde o princípio o meu Deus, o meu Santo? Nós (por tua intervenção) não morreremos. Tu, Senhor, destinaste este povo para aplicar castigos; ó Rochedo, tu o destinaste a executor de sanções.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 13, 'Os teus olhos são limpos demais para ver o mal, e não podes olhar para a tribulação. Por que razão olhas para os que cometem injustiças, e te conservas em silêncio enquanto o ímpio devora o que é mais justo que ele?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 14, '(Se assim fosse, parece que) tratarias os homens como os peixes do mar e como os répteis que não têm dono.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 15, 'Tudo levanta com o anzol, pesca com a sua nassa, recolhe com a sua rede varredoura. Por isso se alegra e exulta;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 16, 'por isso oferece sacrifícios à sua nassa e queima oferendas à sua rede, porque por elas é abundante a sua porção, e o seu manjar escolhido.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 17, 'Continuará ele, portanto, a esvaziar a sua rede, não cessando jamais de devastar as nações?');

-- Capítulo 2
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 2, 20);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 1, 'Estarei alerta (entretanto), fazendo a minha sentinela (como projeta de Israel), e permanecerei de pé sobre as fortificações; olharei atentamente para ver o que me vai dizer o Senhor e o que hei-de responder à advertência recebida.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 2, 'Então respondeu-me o Senhor, dizendo; Escreve o que vês e nota-o sobre tabuinhas (de escrever), para que se possa ler correntemente.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 3, 'Porque a visão é apenas para o tempo devido, mas enfim ela se cumprirá, não faltará; se tardar, espera-a, porque infalivelmente virá, não faltará.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 4, 'Eis que sucumbe o que não tem a alma recta, mas o justo viverá pela sua fidelidade.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 5, 'Assim como o vinho engana quem o bebe, assim o homem soberbo perderá o seu brilho, ele que dilata como o inferno a sua alma, e é insaciável como a morte, que junta sob o seu domínio todas as nações e amontoa junto de si todos os povos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 6, 'Porventura não virá ele a ser a fábula de todos estes, e o objecto dos seus (satíricos) provérbios? Dir-se-á; Ai daquele que acumula o que não é seu até quando? — daquele que acumula sobre si o peso da dívida!'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 7, 'Porventura (ó mau) não se levantarão de repente os teus credores, não despertarão os teus exactores? Serás presa deles.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 8, 'Visto que despojaste muitas nações, despojar-te-ão todos os outros povos, por causa do sangue humano (que derramaste), das violências cometidas contra a terra, contra a cidade e contra todos os seus habitantes.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 9, 'Ai daquele que ajunta ganhos criminosos para (estabelecer a) sua casa, a fim de colocar em lugar muito alto o seu ninho, pensando livrar-se da mão do mal!'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 10, 'Tu meditaste, cobrindo de vergonha a tua casa, arruinar muitos povos, comprometendo a tua própria vida.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 11, 'Porque a pedra clamará da parede (contra ti), e o madeiramento que serve de travação ao edifício, lhe responderá.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 12, 'Ai daquele que edifica uma cidade com sangue e que funda as suas bases na iniquidade!'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 13, 'Porventura o Senhor dos exércitos não fará (como castigo) isto (que se segue)? Os povos trabalharão para o fogo, e as nações fatigar-se-ão para nada. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 14, 'Porque a terra se encherá do conhecimento da glória do Senhor, como o mar está coberto das suas águas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 15, 'Ai daquele que dá de beber ao seu próximo, misturando fel (na bebida) até o embriagar, para ver a sua nudez!'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 16, 'Tu (que assim procedes) serás cheio de ignomínia, em lugar de glória; bebe também até ficares ébrio; voltai-se-á sobre ti o cálice da direita do Senhor, e a abjecção cairá sobre a tua glória.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 17, 'Porque a violência executada contra o Líbano recairá sobre ti, e os estragos dos animais ferozes far-te-ão tremer, por causa do sangue humano (que derramaste) e das injustiças cometidas contra a terra, contra a cidade e contra todos os seus habitantes.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 18, 'De que serve a escultura para que o escultor a faça? O ídolo fundido que só ensina mentiras, para que o artista nele ponha a sua confiança, fabricando divindades mudas?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 19, 'Ai daquele que diz ao pau; Desperta! e à pedra muda: Levanta-te! Porventura poder-lhe-á ela ensinar alguma coisa? Vê que ela está coberta de ouro e de prata, mas nas suas entranhas não há espírito algum.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 20, 'Porém o Senhor está nó seu santo templo; cale-se toda a terra diante dele!');

-- Capítulo 3
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 3, 19);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 1, 'Oração do profeta Habaeuc. No tom das lamentações.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 2, 'Senhor, ouvi a tua mensagem e temi perante as tuas obras. Senhor, faze reviver a tua obra, agora que os anos se aproximam; agora que os anos se aproximam, torna-a manifesta! Quando estiveres irado, tu te lembrarás da (tua) misericórdia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 3, 'Deus vem de Teman, o Santo do Monte de Faran. A sua majestade cobre os céus, e a terra está cheia do seu louvor. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 4, 'O seu resplendor é como a luz; das suas mãos brotam raios; é lá que está escondida a sua fortaleza.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 5, 'A calamidade vai diante da sua face, a febre caminha sobre os seus passos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 6, 'Pára e mede a terra, olha e abala as nações; são reduzidas a pó as montanhas eternas, os outeiros antigos desfazem-se, seus caminhos de sempre.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 7, 'Eu vi na aflição as tendas da Etiópia; os pavilhões da terra de Madian estão turbados.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 8, 'Porventura é contra os rios, Senhor, que estás irado? É contra os rios o teu furor? Ou é contra o mar a tua indignação, quando montas sobre os teus cavalos, sobre teus carros triunfantes?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 9, 'Mostra-se desnudado o teu arco; os juramentos são flechas da tua palavra. Tu fendes a terra, e dela saem torrentes.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 10, 'Os montes, ao verem-te, ficam traspassados de dor: uma tromba de água passa, o abismo faz ouvir a sua voz, levanta as suas mãos ao alto. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 11, 'O sol e a lua pararam na sua morada, avança-se à luz das tuas setas, ao resplendor da tua fulgurante lança.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 12, 'Na tua cólera pisas aos pés a terra; com o teu furor esmagas as nações.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 13, 'Tu saíste para salvação do teu povo, para salvar o teu Ungido. Abateste a casa do ímpio, descobriste os seus alicerces até baixo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 14, 'Atravessaste com os teus dardos o chefe dos seus guerreiros, povo, que vinham como um torvelinho para me destruírem, com gritos de alegria, como se fossem devorar um infeliz no seu esconderijo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 15, 'Lançaste os teus cavalos através do mar, no turbilhão de grandes (massas de) águas,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 16, 'Ouvi (a tua voz), e as minhas entranhas comoveram-se; os meus lábios tremeram a essa voz. Penetra a podridão até aos meus ossos, os meus passos vacilam ao meu peso. Espero silencioso o dia da tribulação, que se deve levantar contra o povo que nos assalta.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 17, 'Porque a figueira não rebentará e as vinhas não deitarão os seus gomos. Faltará o fruto da oliveira, e os campos não darão de comer. As ovelhas desaparecerão do aprisco, e não haverá bois nos estábulos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 18, 'Eu, porém, me regozijarei no Senhor, e exultarei no Deus, meu salvador.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 19, 'Iavé, meu Senhor, é a minha fortaleza, ele que torna os meus pés (velozes) como os dos veados e me faz andar sobre as cumeadas. Ao regente do canto. Para instrumentos de corda. (ver nota)');

