-- undefined (undefined)

-- Capítulo 1
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 1, 18);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 1, 'Palavra do Senhor, que foi dirigida a Sofonias, filho de Cusi, filho de Godolias, filho de Amarias, filho de Bzequias, no tempo de Josias, filho de Amon, rei de Judá. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 2, 'Destruirei tudo sobre a face da terra, diz o Senhor;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 3, 'destruirei os homens e os animais, destruirei as aves do céu e os peixes do mar; farei desaparecer os escândalos com os ímpios; exterminarei da terra os homens, diz o Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 4, 'Estenderei a minha mão contra Judá e contra todos os habitantes de Jerusalém; exterminarei deste lugar os restos (da idolatria) de Baal, até os nomes (ou a memória) dos seus ministros e sacerdotes;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 5, '(exterminarei) os que adoram a milícia (ou os astros) do céu sobre os telhados, os que adoram o Senhor e Juram pelo seu nome, mas ao mesmo tempo juram (realmente) pelo nome de Melcom;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 6, 'e os que deixam de seguir o Senhor, os que não buscam o Senhor, nem procuram encontrá-lo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 7, 'Silêncio diante da face do Senhor Deus, porque o dia (terrível) do Senhor está perto, porque o Senhor preparou um sacrifício, santificou os convidados.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 8, 'No dia do sacrifício do Senhor castigarei (diz Deus) os chefes e os príncipes reais (de Jerusalém) e todos os que se vestem de trajes estrangeiros;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 9, 'castigarei nesse dia todos os que entram com arrogância pelo limiar (do templo) e que enchem de violência e de fraude a casa do seu senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 10, 'Naquele dia haverá, diz o Senhor, muitos clamores à Porta dos Peixes, gemidos das bandas da cidade nova, grande tumulto do lado das colinas. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 11, 'Habitantes do Maktesh lamentai-vos, porque todo o povo dos mercadores foi aniquilado, todos os que traziam cargas de prata pereceram. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 12, 'Naquele tempo acontecerá isto: esquadrinharei Jerusalém com lanternas e castigarei os homens que estão sentados sobre as suas fezes, que dizem nos seus corações: O Senhor não faz bem nem mal (a ninguém). (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 13, 'As suas riquezas serão saqueadas, as suas casas devastadas; edificarão casas, mas não as habitarão; plantarão vinhas, mas não lhes beberão o vinho.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 14, 'O dia grande do Senhor está próximo; está próximo, vai chegando com velocidade! Tremendo é o ruído do dia do Senhor; o forte se verá nele em grande aperto.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 15, 'Esse dia será um dia de ira, um dia de tribulação e angústia, um dia de calamidade e miséria, um dia de trevas e escuridão, um dia de nuvens e espesso nevoeiro,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 16, 'um dia de trombeta e de gritos guerreiros contra as cidades fortificadas e contra as torres elevadas. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 17, 'Atribularei os homens, e eles andarão como cegos, porque pecaram contra o Senhor; o seu sangue será espalhado como poeira, e os seus corpos serão (tratados) como esterco.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 18, 'Nem a sua prata, nem o seu ouro os poderão livrar no dia da ira do Senhor; no fogo do seu zelo será devorada toda a terra, porque ele se apressará a exterminar completamente todos os habitantes da mesma terra.');

-- Capítulo 2
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 2, 15);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 1, 'Vinde todos, Juntai-vos (ó Israelitas), nação despudorada,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 2, 'antes que o decreto (do Senhor) produza esse dia que passará como (um turbilhão de) pó, antes que venha sobre vós a ira do furor do Senhor, antes que venha sobre vós o dia da indignação do Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 3, 'Buscai o Senhor todos vós, os humildes nesta terra, vós os que guardais os seus preceitos; buscai a justiça, buscai a mansidão, para ver se podeis achar um abrigo no dia do furor do Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 4, 'Com efeito, Gaza será abandonada e Ascalon virá a ser um deserto. Azot será assolada em pleno meio-dia, e Acaron arrancada pela raiz.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 5, 'Ai de vós, os que habitais a costa do mar, ai do povo dos cretenses! Canaan, terra, dos Filisteus, uma palavra do Senhor está para cair sobre vós: Exterminar-te-ei, sem que fique um só dos teus habitantes. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 6, 'A costa do mar será então lugar de repouso para os pastores e aprisco para as ovelhas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 7, 'Esta região será daqueles que tiverem ficado da casa de Judá; eles encontrarão pastagens e descansarão durante a noite nas casas de Ascalon, porque o Senhor seu Deus os visitará e os restaurará.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 8, 'Ouvi as afrontas de Moab e os insultos dos filhos de Amon, que ultrajaram o meu povo e se ensoberbeceram com o seu território.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 9, 'Por isso, juro por vida minha, diz o Senhor dos exércitos, o Deus de Israel, que Moab virá a ser como Sodoma, e os filhos de Amon como Gomorra: lugar de urtigas, região de sal, um deserto eterno. Os restos do meu povo os saquearão, os que restarem da minha gente serão os seus donos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 10, 'Isto lhes há-de acontecer por castigo da sua soberba, porque insultaram e trataram com arrogância o povo do Senhor dos exércitos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 11, 'O Senhor se mostrará terrível contra eles, e aniquilará todos os deuses da terra. E adorá-lo-ão, cada um no seu país, todos os habitantes das ilhas das nações. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 12, 'Também vós, ó Etíopes, sereis mortos pela minha espada.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 13, 'Estenderá a sua mão contra o aquilão, destruirá Assur, reduzirá Nínive a uma solidão, árida como um deserto.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 14, 'Rebanhos descansarão no meio dela, e bandos de animais de toda a espécie; o pelicano e o ouriço terão por morada os seus capitéis; ouvir-se-á o canto das aves por cima das janelas, o corvo por cima das portas, porque aniquilarei a cidade.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 15, 'Esta é aquela cidade alegre, que nada temia, que dizia no seu coração: Eu, e nada mais senão eu! Como se mudou ela num deserto, num covil de feras? Todo o que passar por ela, insultá-la-á com assobios e agitará a mão (em sinal de desprezo).');

-- Capítulo 3
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 3, 20);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 1, 'Ai da (cidade) rebelde e imunda, da cidade opressora!'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 2, 'Ela não ouviu a voz (que a admoestava), nem recebeu o aviso; não confiou no Senhor, não se aproximou do seu Deus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 3, 'Os seus chefes são no meio dela como leões rugindo; os seus juízes como lobos nocturnos, que não deixam nada (da presa) para a manhã seguinte.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 4, 'Os seus profetas são impostores e pérfidos, os seus sacerdotes profanam as coisas santas, procedem contra a lei.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 5, 'O Senhor, que é justo e que está no meio dela, não faz iniquidade; de manhã estabelece à luz o seu juízo, sem falta; o ímpio, porém, não sabe que coisa é ter vergonha.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 6, 'Exterminei as nações (tuas inimigas, diz Deus); as suas torres foram deitadas abaixo; tornei os seus caminhos desertos, sem haver mais quem por eles passe; as suas cidades foram saqueadas, não havendo já um homem nelas, (não havendo) habitante algum.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 7, 'Eu disse: Ao menos depois disto (ó Israel) temer-me-ás, aproveitar-te-ás dos meus avisos; a tua casa não será arruinada por causa de todos os crimes, pelos quais eu já a castiguei. Todavia (os teus filhos), apressaram-se a tornar ainda mais detestáveis as suas obras.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 8, 'Portanto, esperai-me, diz o Senhor, para o dia em que me hei-de levantar como testemunha, porque resolvi congregar as nações e reunir os reinos; (então) derramarei sobre eles a minha indignação, toda a ira do meu furor, porque toda a terra será devorada pelo fogo do meu zelo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 9, 'Então darei aos povos lábios puros, para que todos invoquem o nome do Senhor e o sirvam de comum acordo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 10, 'Da outra banda dos rios da Etiópia virão os meus adoradores, os meus filhos dispersos, trazer-me os seus presentes.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 11, 'Naquele dia (ó Jerusalém) não serás confundida por causa de todos os teus pecados cometidos contra mim, porque então exterminarei do meio de ti aqueles que, com as suas palavras faustosas, excitavam a tua soberba, e tu, para o futuro, não te orgulharás mais por possuires o meu santo monte (de Sido).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 12, 'Deixarei subsistir no meio de ti um povo pobre e humilde, que esperará no nome do Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 13, 'Os que restarem de Israel não cometerão iniquidades, não proferirão a mentira; não se achará na sua boca língua enganosa, porquanto serão apascentados e repousarão, sem haver quem lhes canse medo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 14, 'Solta gritos de júbilo, filha de Sião! Solta gritos de alegria, ó Israel! Alegra-te e exulta de todo o coração, filha de Jerusalém!'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 15, 'O Senhor apagou a sentença da tua condenação, afastou de ti os teus inimigos; o Senhor que é o rei de Israel, está no meio de ti; não temerás mais a desgraça.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 16, 'Naquele dia dir-se-á a Jerusalém: Não temas; não se enfraqueçam as tuas mãos, ó Sião.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 17, 'O Senhor teu Deus, herói salvador, está no meio de ti! Por causa de ti anda em transportes de alegria, cala-se no seu amor, exulta jubiloso a teu respeito. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 18, 'Eu congregarei esses homens vãos, que se tinham afastado da lei, visto que eles te pertenciam, a fim de que tenhas mais vergonha por causa deles,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 19, 'Eis que, naquele tempo, matarei todos os que te afligirem, salvarei os coxos, recolherei os dispersos e fá-los-ei gloriosos e afamados em todos os países onde sofreram ignomínia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 20, 'Naquele tempo em que vos fizer tornar, no tempo em que vos juntar todos, tornar-vos-ei célebres e gloriosos entre todos os povos da terra, quando tiver realizado, diante dos vossos olhos, a vossa restauração, diz o Senhor.');

