-- undefined (undefined)

-- Capítulo 1
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 1, 21);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 1, 'No oitavo mês, no segundo ano do reinado de Dario, foi dirigida ao profeta Zacarias, filho de Baraquias, filho de Ado, a palavra do Senhor, nestes termos:'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 2, 'O Senhor irou-se em extremo contra vossos pais.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 3, 'Tu dirás (a estes seus filhos): Assim fala o Senhor dos exércitos: Voltai outra vez a mim, diz o Senhor dos exércitos, e ou voltarei de novo a vós, diz o Senhor dos exércitos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 4, 'Não sejais como vossos pais, aos quais os profetas que vos precederam lançaram este apelo: Isto diz o Senhor dos exércitos: Convertei-vos dos vossos maus caminhos, das vossas malvadas acções. Eles não me ouviram, não me deram atenção, diz o Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 5, 'Onde estão já vossos pais? E porventura vivem os profetas eternamente? (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 6, 'Mas as minhas palavras e as minhas ordens dadas aos meus servos, os profetas, acaso não atingiram vossos pais? (Sim, e de tal forma que) eles então se converteram, dizendo: Como o Senhor dos exércitos fez tenção de nos tratar, segundo os nossos caminhos e segundo as nossas obras, assim de facto nos tratou. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 7, 'No segundo ano do reinado de Dario, aos vinte e quatro dias do mês undécimo, que é o mês (chamado) de Sabat, foi dirigida ao profeta Zacarias, filho de Baraquias, filho de Ado, a palavra do Senhor, nestes termos:'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 8, 'Tive de noite uma visão: Apareceu-me um homem montado num cavalo vermelho, parado entre umas murteiras, que havia no fundo do vale; atrás dele estavam mais cavalos, uns ruivos, outros alazões, e outros brancos. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 9, 'Eu disse: Quem são estes. Senhor meu? E o anjo que falava comigo disse-me: Vou mostrar-te quem são estes. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 10, 'O homem que estava parado entre as murteiras tomou a palavra e disse: Estes são os que o Senhor enviou a percorrer a terra.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 11, 'Então eles dirigiram-se ao anjo do Senhor, que estava entre as murteiras, e disseram-lhe; Nós temos percorrido a terra, e eis que toda a terra (vizinha de Israel) está habitada e em repouso.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 12, 'O anjo do Senhor disse: Senhor dos exércitos, até quando diferirás tu o compadecer-te de Jerusalém e das cidades de Judá, contra as quais estás irritado, há setenta anos?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 13, 'Neste ponto o Senhor, dirigindo-se ao anjo que falava comigo, disse-lhe boas palavras, palavras de consolação.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 14, 'E o anjo que falava comigo disse-me: Proclama o seguinte: Isto diz o Senhor dos exércitos: Eu sinto um grande zelo por Jerusalém e por Sião,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 15, 'e estou sumamente irritado contra estas nações que vivem satisfeitas, porque eu somente estava um pouco agastado (contra Israel), mas elas excederam a medida (do castigo que eu planeava).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 16, 'Portanto isto diz o Senhor: Volto novamente para Jerusalém com entranhas de misericórdia; a minha casa será nela reedificada, diz o Senhor dos exércitos, e o cordel será estendido sobre Jerusalém (para a reconstruir).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 17, 'Proclama ainda o seguinte: Assim fala o Senhor dos exércitos: As minhas cidades ainda hão-de ser Cheias de bens; o Senhor ainda consolará Sião, ainda escolherá Jerusalém.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 18, 'Em seguida levantei os meus olhos, pus-me a olhar e vi quatro hastes.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 19, 'Perguntei ao anjo que falava comigo: Que é isto? Respondeu-me: Estas são as hastes que dispersaram Judá, Israel e Jerusalém,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 20, 'Depois o Senhor mostrou-me quatro ferreiros.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 21, 'Eu perguntei: Que vêm estes fazer? Respondeu-me: Aquelas hastes haviam dispersado Judá de forma que ninguém ousava levantar a cabeça; mas estes vieram para as deitar abaixo, para abater as hastes (ou o poder) das nações, que levantaram a sua força contra o pais de Judá, para dispersar (os seus habitantes).');

-- Capítulo 2
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 2, 13);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 1, 'Levantei os meus olhos, pus-me a olhar e vi um homem que tinha na sua mão um cordel de medir.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 2, 'Interroguei-o: Para onde vais tu? Respondeu-me: Vou medir Jerusalém, ver qual é a sua largura e qual o seu comprimento.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 3, 'E eis que apareceu o anjo que falava comigo, e outro anjo veio-lhe ao encontro'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 4, 'e disse-lhe: Corre, fala a este jovem assim: Jerusalém será habitada sem muros, por causa da multidão de homens e de animais que haverá no meio dela.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 5, 'Eu mesmo, diz o Senhor, serei para ela um muro de fogo, que a cercará, serei no meio dela a sua glória.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 6, 'De pé! De pé! Fugi da terra do aquilão, diz o Senhor, porque eu vos espalhei para os quatro ventos do céu, diz o Senhor, (somente para vos castigar). (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 7, 'Salva-te ó Sião, que habitas na cidade de Babilônia!'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 8, 'Porque isto diz o Senhor dos exércitos: Para glória me enviou o Senhor contra as nações que vos despojaram : aquele que tocar em vós, toca na menina dos seus olhos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 9, 'Eis que vou levantar a minha mão contra estes povos, e eles virão a ser presa daqueles que eram seus escravos; assim conhecereis que o Senhor dos exércitos é que me enviou.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 10, 'Filha de Sião, entoa cânticos, alegra-te, porque eis que venho para habitar no meio de ti, diz o Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 11, 'Naquele dia se chegarão muitas nações ao Senhor, e serão o meu povo; habitarei no meio de ti, e saberás que o Senhor dos exércitos é que me enviou a ti. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 12, 'O Senhor possuirá Judá, como sua porção na terra santa, e escolherá outra vez Jerusalém.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 13, 'Toda a carne esteja em silêncio diante da face do Senhor, porque ele se levantou da sua santa habitação.');

-- Capítulo 3
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 3, 10);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 1, 'Depois O Senhor mostrou-me o sumo sacerdote Josué, que estava em pé diante do anjo do Senhor; Satanás estava à sua direita para se lhe opôr.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 2, 'O (anjo do) Senhor disse a Satanás: O Senhor te reprima, ó Satanás; reprima-te o Senhor que escolheu (para si) Jerusalém. Porventura não é este (Josué, como que) um tição que foi tirado do fogo? (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 3, 'Ora Josué estava revestido de hábitos sujos, e posto em pé diante do anjo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 4, 'Este tomou a palavra e falou aqueles que estavam diante dele, dizendo; Tirai-lhe esses hábitos sujos. Depois disse a Josué: Eis que tirei de ti a tua iniquidade e te revesti de roupas de gala.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 5, 'E acrescentou: Ponde-lhe na cabeça uma tiara limpa. E puseram-lhe na cabeça uma tiara limpa e revestiram-no de preciosos vestidos. Entretanto o anjo do Senhor estava de pé.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 6, 'Em seguida, o anjo do Senhor fez esta declaração a Josué;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 7, 'Isto diz o Senhor dos exércitos: Se andares nos meus caminhos, se observares tudo o que tenho mandado que se observe, governarás a minha casa, guardarás os meus átrios, e eu te darei lugar entre estes que estão aqui presentes.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 8, 'Ouve, ó Josué, sumo sacerdote, tu e os teus colegas, que se sentam junto de ti — porque são homens que simbolizam o futuro — Eis que farei vir o meu servo Germen. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 9, 'Eis a pedra que pus diante de Josué; sobre esta pedra única estão sete olhos; eis que eu mesmo a lavrarei com o cinzel, diz o Senhor dos exércitos, e num só dia tirarei a iniquidade desta terra.1'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 10, 'Naquele dia, diz o Senhor dos exércitos, cada um chamará o seu amigo para debaixo da sua videira e da sua figueira.');

-- Capítulo 4
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 4, 14);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 1, 'O anjo que falava comigo voltou e despertou-me, como a um homem a quem despertam do seu sono.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 2, 'Perguntou-me: Que vês tu? Respondi: Vejo um candeeiro todo de ouro, que tem um depósito no alto, sete lâmpadas sobre os seus braços e sete canais para (fazer correr o azeite para) as lâmpadas que estão no alto do candeeiro.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 3, 'Há também por cima dele duas oliveiras: uma à direita do depósito e outra à sua esquerda.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 4, 'Então retomei a palavra e disse ao anjo que falava comigo: Meu Senhor, que quer isto dizer?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 5, 'O anjo que falava comigo respondeu: Não sabes o que isto é? Respondi: Não, meu Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 6, 'Então ele explicou: Esta é a palavra que o Senhor dirige a Zorobabel: Nem por meio dum exército, nem pela força, mas sim pelo meu Espírito, diz o Senhor dos exércitos. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 7, 'Quem és tu, ó grande monte (de dificuldades)? Diante de Zorobabel, torna-te uma planície. Ele porá a pedra de remate, em meio de aclamações: Graça, graça a ela!'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 8, 'Foi-me dirigida a palavra do Senhor, nestes termos:'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 9, 'As mãos de Zorobabel puseram os fundamentos desta casa, as suas mãos a hão-de acabar. Assim saberás que o Senhor dos exércitos me enviou a vós.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 10, 'Porque, quem desprezaria este dia de pequenas coisas? Alegrar-se-ão quando virem o fio de prumo na mão de Zorobabel. Estes sete olhos são os olhos do Senhor, que discorrem por toda a terra. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 11, 'Retomei a palavra e disse-lhe: Que significam estas duas oliveiras, uma à direita do candeeiro, e outra à sua esquerda?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 12, 'De novo interroguei: Que significam estes dois ramos de oliveira, que, por dois tubos de ouro, deixam correr o ouro (isto é, azeite dourado)?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 13, 'Ele respondeu-me: Não sabes o que Isto significa? Eu disse; Não, meu Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 14, 'Ele explicou: Estas duas oliveiras são os dois ungidos que assistem diante do Senhor de toda a terra (como seus ministros). (ver nota)');

-- Capítulo 5
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 5, 11);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 1, '(Em seguida) levantei os olhos, pus-me a olhar e vi um livro que voava.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 2, '(O anjo) disse-me; Que vês tu? Respondi: Vejo um livro que voa, o qual tem vinte côvados de comprido e dez côvados de largo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 3, 'Então disse-me (o anjo): Esta é a maldição que vai difundir-se sobre a face de todo o país; todo o ladrão será expulso por ela, e todo o que jura (falso) será, da mesma sorte, lançado fora por ela. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 4, 'Eu a deixarei espalhar-se, diz o Senhor dos exércitos, e ela irá à casa do ladrão, e à casa do que jura falsamente em meu nome; ficará no meio da casa (de cada um) deles e a consumirá com a sua madeira e as suas pedras.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 5, 'O anjo que falava comigo, aproximou-se e disse-me; Levanta os olhos e vê o que aparece.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 6, 'Eu disse: Que é isto? Ele respondeu-me: É um efa que aparece. E acrescentou: É a iniquidade deles em toda a terra.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 7, 'Depois vi que era levantado um disco de chumbo e reparei que uma mulher estava sentada no efa. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 8, 'Então disse (o anjo): Eis a iniquidade. E precipitou-a no fundo do efa e tapou a boca do efa com o disco de chumbo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 9, 'Depois levantei os olhos e olhei: apareceram duas mulheres, e o vento soprava nas suas asas; tinham asas como as duma cegonha. E levantaram o efa entre a terra e o céu.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 10, 'Eu disse ao anjo que falava comigo: Para onde levam elas o efa?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 11, 'O anjo respondeu-me: Para a terra de Senaar a fim de que lhe seja edificada uma casa, e fique ali colocada e posta sobre a sua base (a iniquidade).');

-- Capítulo 6
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 6, 15);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 1, 'De novo levantei os olhos e olhei : vi quatro carros que saíam dentre duas montanhas, e estas duas montanhas eram montanhas de bronze. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 2, 'No primeiro carro havia cavalos vermelhos, no segundo carro havia cavalos negros,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 3, 'no terceiro carro havia cavalos brancos, e no quarto carro havia cavalos malhados, fortes.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 4, 'Tomei a palavra e disse ao anjo que falava comigo: Que significam estas coisas, meu Senhor?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 5, 'O anjo respondeu-me: Estes são os quatro ventos do céu, que saem para estar diante do Senhor de toda a terra (a fim de executar as suas ordens). (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 6, 'Os cavalos negros, seguem para a terra do aquilão, os brancos para oriente, os baios para a terra do meio-dia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 7, 'Os (cavalos) vigoroso, logo que saíram, pediram para percorrer toda a terra. E (o anjo) disse-Ihes: Ide, percorrei a terra. E eles percorreram a terra.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 8, 'Depois chamou-me e disse: Os que se dirigiram para a terra do aquilão, fizeram repousar o meu espírito na terra do aquilão.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 9, 'Foi-me dirigida a palavra do Senhor, nestes termos :'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 10, 'Recebe o que te derem os exilados, as ofertas de Holdai, Tobias e Idaia; irás neste mesmo dia e entrarás em casa de Josias, filho de Sofonias, os quais vieram de Babilônia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 11, 'Tomarás prata e ouro, e farás coroas, que porás sobre a cabeça do sumo sacerdote Josué, filho de Josedec.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 12, 'Falar-lhe-ás desta maneira: Assim fala o Senhor dos exércitos: Eis o homem cujo nome é Germen: onde ele está, alguma coisa há-de germinar. Ele é que há-de edificar o templo do Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 13, 'Reconstruirá o templo do Senhor, usará insígnias reais, sentar-se-á e dominará sobre o seu trono; será sacerdote sobre o seu trono, e haverá entre os dois uma perfeita paz. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 14, 'Estas coroas serão para Helem, Tobias, Idaia e Hen, filho de Sofonias, como um monumento no templo do Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 15, 'Homens que estão longe, virão e trabalharão na fábrica do templo do Senhor, e vós sabereis que o Senhor dos exércitos é que me enviou a vós. Isto acontecerá, se ouvirdes com submissão a voz do Senhor vosso Deus.');

-- Capítulo 7
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 7, 14);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 1, 'No ano quarto do reinado de Dario, foi dirigida a palavra do Senhor a Zacarias, no dia quarto do nono mês, que é o de Casleu.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 2, 'Betel enviou Sarasar, Rogomelec e os homens que estavam com ele para apresentar as suas orações diante do Senhor'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 3, 'e fazer aos sacerdotes da casa do Senhor dos exércitos e aos profetas esta pergunta: Porventura devo eu chorar no quinto mês, jejuando, como já o fiz durante muitos anos (Que durou o cativeiro)? (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 4, 'Foi-me dirigida a palavra do Senhor dos exércitos, nestes termos: (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 5, 'Dize a todo o povo do pais e aos sacerdotes o seguinte: Quando vós jejuáveis e choráveis no quinto e sétimo mês, durante estes setenta anos, foi por meu respeito que jejuastes?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 6, 'Quando comestes e bebestes, não foi para vós que comestes e bebestes?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 7, 'Porventura não são estas as coisas que disse o Senhor por meio dos profetas que nos precederam, quando Jerusalém era ainda habitada e estava Cheia de riquezas, ela e as cidades circunvizinhas, e quando havia população em Negueb e Sefeíah? (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 8, 'Foi dirigida a Zacarias a palavra do Senhor, nestes termos:'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 9, 'Assim fala o Senhor dos exércitos: Julgai segundo a verdadeira justiça, e cada um de vós exerça com seu irmão obras de amor e de misericórdia,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 10, 'Não oprimais a viúva, nem o órfão, nem o estrangeiro, nem o pobre; nenhum forme no seu coração maus desígnios contra os outros.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 11, 'Porém eles não quiseram atender (à minha voz), antes se retiraram voltando-me as costas, e taparam os seus ouvidos para não ouvirem.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 12, 'Tornaram o seu coração (duro) como um diamante, para não ouvirem o ensinamento e as palavras que o Senhor dos exércitos lhes dirigia pelo seu Espírito, por meio dos profetas do passado. Por isso se acendeu contra eles uma grande indignação do Senhor dos exércitos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 13, 'Sucedeu que (o Senhor) os chamou e que eles não o ouviram. Assim, quando eles gritarem, eu não os ouvirei, diz o Senhor dos exércitos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 7), 14, 'Dispersei-os por todos os reinos que lhes eram desconhecidos; atrás deles ficou o país desolado, não havendo quem por ele transitasse. Transformaram num deserto uma terra de delícias.');

-- Capítulo 8
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 8, 23);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 1, 'A palavra do Senhor dos exércitos fez-se ouvir, nestes termos:'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 2, 'Isto diz o Senhor dos exércitos; Tenho grande zelo por Sião, zelo-a com grande cólera (contra os seus inimigos).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 3, 'Isto diz o Senhor dos exércitos: Volto para Sião, venho habitar no meio de Jerusalém; Jerusalém chamar-se-á a cidade da fidelidade, e o monte do Senhor dos exércitos monte santo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 4, 'Isto diz o Senhor dos exércitos: Ainda nas praças de Jerusalém se verão velhos e velhas, tendo cada um na mão um cajado por causa da sua muita idade;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 5, 'os largos da cidade estarão cheios de meninos e meninas, que brincarão nas suas praças.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 6, 'Isto diz o Senhor dos exércitos: Se o que eu predigo para esse tempo parecer impossível aos olhos dos que restarem deste povo, acaso será .isso impossível a meus olhos? — diz o Senhor dos exércitos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 7, 'Assim fala o Senhor dos exércitos: Eis que vou livrar o meu povo, tirando-o da terra do oriente e da terra do ocidente.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 8, 'Eu os trarei, e eles habitarão no meio de Jerusalém; serão o meu povo, e eu serei o seu Deus na fidelidade e na justiça.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 9, 'Isto diz o Senhor dos exércitos: Confortem-se as vossas mãos, ó vós, que nestes dias ouvis estas palavras da boca dos profetas, agora que foram lançados os fundamentos da casa do ''Senhor dos exércitos, para que o templo seja reedificado.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 10, 'Antes destes dias, não havia salário para os homens, nem tinham paga os animais, nem havia paz para o que entrava nem para o que saía, por causa do inimigo; eu tinha deixado todos os homens uns contra os outros.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 11, 'Agora, porém, não tratarei os restos deste povo como nos dias antigos, diz o Senhor dos exércitos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 12, 'A sementeira é de paz: a vinha dará o seu fruto, a terra os seus produtos, os céus darão o seu orvalho, e eu farei que os restos deste povo possuam todos estes bens.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 13, 'Acontecerá que, assim como vós éreis uma maldição entre as nações, ó casa de Judá e casa de Israel, assim vos salvarei, e vós sereis uma bênção. Não temais, armem-se as vossas mãos de fortaleza.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 14, 'Isto diz o Senhor dos exércitos: Assim como resolvi afligir-vos, quando vossos pais me provocaram a ira, diz o Senhor,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 15, 'e não voltei atrás, assim, resolvo, pelo contrário, nestes dias fazer bem à casa de Judá e a Jerusalém. Não temais.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 16, 'Eis o que deveis fazer: Falai verdade, uns aos outros, julgai às vossas portas segundo a verdade e para a paz.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 17, 'Nenhum forme no seu coração maus desígnios contra os outros; não gosteis de fazer juramentos falsos, porque todas estas coisas eu as aborreço, diz o Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 18, 'Foi-me dirigida a palavra do Senhor dos exércitos, nestes termos:'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 19, 'Isto diz o Senhor dos exércitos; O jejum do quarto (mês), o jejum do quinto, o jejum do sétimo e o jejum do décimo mês converter-se-ão para a casa de Judá em gozo e alegria, em festivas solenidades. Mas amai a verdade e a paz.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 20, 'Isto diz o Senhor dos exércitos: Virão povos e habitantes de grandes cidades.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 21, 'Os seus habitantes irão ter uns com os outros, dizendo: Vamos e apresentemos as nossas preces na presença do Senhor, busquemos o Senhor dos exércitos. Pela minha parte (dirá cada um), irei.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 22, 'Então virão muitos povos e poderosas nações buscar o Senhor dos exércitos em Jerusalém, fazer as suas orações na presença do Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 8), 23, 'Isto diz o Senhor dos exércitos: Naqueles dias, dez homens de todas as línguas das nações lançarão mão de um judeu, agarrarão a fímbria do seu vestido, dizendo: Iremos convosco, porque soubemos que (o verdadeiro) Deus está convosco. (ver nota)');

-- Capítulo 9
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 9, 17);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 1, 'Oráculo. A palavra do Senhor (pesa) sobre a terra de Hadrac, repousa em Damasco, porque ao Senhor pertencem as cidades de Aram, assim como todas vizinhas as tribos de Israel.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 2, '(Este oráculo é) também contra Hamat, que confina com Damasco e contra Tiro e Sidónia, apesar da sua sabedoria.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 3, 'Tiro levantou as suas fortificações, amontoou prata como terra, e ouro como lama das ruas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 4, 'Eis que o Senhor se apoderará dela, precipitará a sua fortaleza no mar, e será devorada pelo fogo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 5, 'Ascalon verá isto e ficará a tremer; vê-lo-á também Gaza e ficará possuída de intensa dor; Acaron se afligirá, porque foi enganada a sua esperança; em Gaza não haverá mais rei, e Ascalon ficará despovoada. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 6, 'O estrangeiro (conquistador) terá a sua residência em Azot, e eu destruirei a soberba dos Filisteus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 7, 'Tirarei da boca deste povo o sangue, e as suas abominações dentre os seus dentes; ele também será um resto para o nosso Deus, será como uma família em Judá; Acaron será tratado como um Jebuseu. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 8, 'Acamparei em volta da minha casa, guardando-a das idas e vindas (do inimigo); o opressor não passará mais por aí, porque eu olho agora para ela com olhos favoráveis.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 9, 'Salta de alegria, ó filha de Sião, enche-te de júbilo, ó filha de Jerusalém. Eis que o teu rei vem a ti, justo e vitorioso; ele é humilde e vem montado sobre um jumento, sobre o potrinho duma jumenta. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 10, 'Então exterminarei os carros de guerra de Efraim e os cavalos de Jerusalém; os arcos que servem na guerra serão quebrados. Ele anunciará a paz às nações; o seu poder se estenderá de um mar até ao outro mar, desde o rio até às extremidades da terra.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 11, 'Quanto a ti, também, por causa do sangue da tua aliança, farei sair os teus cativos da fossa em que não há água. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 12, 'Tornai para a vossa praça forte, ó cativos (cheios) de esperança: hoje também vos anuncio que vos darei dobrados bens.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 13, 'Porque reteso Judá como um arco, ponho Efraim como flecha; suscitarei os teus filhos, ó Sião, contra os teus filhos, ó Grécia; e te farei (irresistível) como a espada dos valentes. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 14, 'O Senhor Deus aparecerá sobre eles (os Judeus), e a sua flecha partirá como relâmpago; O Senhor Deus os animará pelo som da trombeta e marchará entre as borrascas do meio-dia. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 15, 'O Senhor dos exércitos os protegerá; eles devorarão (os seus inimigos) e os sujeitarão com as pedras das suas fundas; bebendo (o seu sangue), se embriagarão como com vinho, ficarão cheios como os copos e como os ângulos do altar.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 16, 'O Senhor seu Deus os salvará naquele dia, como rebanho do seu povo; à maneira de pedras santas, brilharão sobre a sua terra.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 9), 17, 'Que felicidade, que beleza a dele! O trigo dará crescimento aos jovens, e o vinho novo às virgens. (ver nota)');

-- Capítulo 10
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 10, 11);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 1, 'Pedi ao Senhor chuvas serôdias, e o Senhor fará brilhar o relâmpago, dar-vos-á chuvas em abundância, a cada um erva no campo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 2, '(Como já vistes) os terafins deram respostas vãs,os adivinhos tiveram visões mentirosas; os sonhos apresentados são vãos, as consolações são consolações falsas; por isso (os vossos crédulos pais) foram levados como um rebanho, foram afligidos, porque não tinham pastor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 3, 'O meu furor acende-se contra os pastores, castigarei os bodes. Sim, o Senhor dos exércitos terá cuidado do seu rebanho, da casa de Judá, e fará dela como que o seu cavalo de glória na guerra. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 4, 'De Judá sairá o ângulo, dele a estaca, dele o arco de guerra, dele todos os chefes.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 5, 'Serão como heróis que, nas refregas, pisarão aos pés o inimigo, como a lama das ruas; pelejarão valorosamente, porque o Senhor está com eles; e por eles serão confundidos os cavaleiros (dos seus adversários).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 6, 'Fortalecerei a casa de Judá, salvarei a casa de José; restabelecê-los-ei porque me compadecerei deles; serão como se os não tivesse rejeitado, porque eu sou o Senhor seu Deus: ouvi-los-ei.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 7, '(Os de) Efraim serão como heróis, e o seu coração se alegrará como (com) o vinho; os seus filhos os verão e se alegrarão, e o seu coração exultará no Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 8, 'Eu lhes assobiarei e os congregarei, porque os resgatei; multiplicá-los-ei, como antes se tinham multiplicado.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 9, 'Semeá-los-ei por entre os povos, e eles de longe de recordarão de mim; instruirão seus filhos, e tomarão a vir.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 10, 'Reconduzi-los-ei da terra do Egipto, congregá-los-ei da Assíria, introduzi-los-ei na terra de Galaad e no Líbano, e não se achará lá lugar (bastante) para eles (por serem numerosos).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 10), 11, 'Israel passará o mar, do Egipto, (o Senhor) ferirá as ondas do mar, todas as profundidades do Nilo ficarão descobertas. A soberba de Assur será humilhada, e o ceptro do Egipto será tirado.');

-- Capítulo 11
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 11, 17);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 1, 'Abre, ó Líbano, as tuas portas, e devore o fogo os teus cedros.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 2, 'Lamenta-te, cipreste, porque os cedros caíram, porque as (árvores) magníficas foram destruídas; gemei, carvalhos de Basan, porque o espesso bosque foi cortado.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 3, 'Ouve-se a lamentação dos pastores (ou chefes), porque a sua grandeza foi destruída; ouvem-se os rugidos dos leões, porque a soberba do Jordão foi aniquilada.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 4, 'Isto diz o Senhor meu Deus: Apascenta estas ovelhas destinadas para o matadouro,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 5, 'as quais os seus donos matam sem se compadecerem delas, cujos vendedores dizem; Bem-dito seja o Senhor, que estou rico! — sem que os seus próprios pastores tenham compaixão delas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 6, 'Eu, pois, não perdoarei mais aos habitantes desta terra, diz o Senhor; entregarei os homens uns aos outros, e nas mãos do seu rei; arruinarão o país, e não livrarei ninguém da sua mão.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 7, 'Então pus-me a apascentar as ovelhas destinadas ao matadouro para os mercadores.Então (diz: o profeta) tomei dois cajados, a um dos quais chamei Graça, e a outro União, e levei o rebanho a pastar. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 8, 'Suprimi três pastores num mês. Depois perdi a paciência com as ovelhas, e também elas se aborreceram de mim.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 9, 'Eu disse: Não vos apascentarei mais; o que morre, morra; o que se corta, corte-se; e os que escaparam, que se devorem uns aos outros.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 10, 'Eu então tomei o cajado que se chamava Graça, e quebrei-o para assim desfazer a aliança que tinha feito com todos os povos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 11, 'Ficou quebrado naquele dia, e os mercadores do rebanho, que me observavam, reconheceram assim que isto era palavra do Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 12, 'Eu disse-lhes: Se vos parece bem, dai-me o salário que me é devido (já que não me quereis por pastor); se não, guardai-o. Então pagaram-me pelo meu salário trinta moedas de prata.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 13, 'O Senhor disse-me: Arroja ao oleiro esse dinheiro, essa bela soma pela qual me apreciaram. Tomei as trinta moedas de prata e lancei-as na casa do Senhor para o oleiro.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 14, 'Depois quebrei o meu segundo cajado que se chamava União, para dissolver a fraternidade entre Judá e Israel.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 15, 'O Senhor disse-me: Aparelha-te agora como um pastor insensato.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 16, 'Com efeito, eis que vou suscitar na terra um pastor que não visitará as ovelhas abandonadas, que não buscará as que se desgarram, que não curará a doente, que não sustentará a sã, mas que comerá a carne das gordas e quebrará as suas unhas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 11), 17, 'Ai do mau pastor, que abandona o rebanho! Que a espada caia sobre o seu braço e sobre o seu olho direito! Que se seque o seu braço e que o seu olho direito seja coberto de trevas.');

-- Capítulo 12
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 12, 14);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 1, 'Oráculo. Palavra do Senhor contra Israel. Palavra do Senhor, que estendeu o céu, fundou a terra e formou o espírito que o homem tem dentro de si:'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 2, 'Eis que farei de Jerusalém um copo inebriante para todos os povos circunvizinhos. Esta palavra é também para Judá, quando se cercar Jerusalém.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 3, 'Naquele dia farei de Jerusalém uma pedra pesada para todos os povos; todos aqueles que a levantarem, ficarão magoados; coligar-se-ão contra ela todos os reinos da terra.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 4, 'Naquele dia, diz o Senhor, ferirei de pasmo todos os cavalos, e de delírio os que montam neles; abrirei os meus olhos sobre a casa de Judá, mas ferirei de cegueira os cavalos de todos os povos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 5, 'Então dirão os chefes de Judá no seu coração; A força dos habitantes de Jerusalém reside no Senhor dos exércitos, seu Deus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 6, 'Naquele dia farei que os chefes de Judá sejam como um tição de fogo, que se mete debaixo da lenha, como um facho aceso entre a palha; devorarão à direita e à esquerda todos os povos circunvizinhos, e Jerusalém permanecerá firme no seu lugar.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 7, 'O Senhor salvará as tendas de Judá, para que a altivez da casa de Davide e a dos habitantes de Jerusalém não se elevem em detrimento de Judá. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 8, 'Naquele dia o Senhor protegerá os habitantes de Jerusalém: o mais fraco dentre eles será (tão valente) como Davide, e a casa de Davide surgirá aos olhos deles como Deus, como um anjo do Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 9, 'Naquele dia procurarei esmagar todas as nações que vierem contra Jerusalém.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 10, 'Derramarei sobre a casa de Davide e sobre os habitantes de Jerusalém um espírito de graça e de preces, e eles porão os olhos em mim. Quanto àquele que traspassaram, chorá-lo-ao com pranto, como se chora um filho único, terão dele um sentimento, como se costuma ter na morte de um primogênito.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 11, 'Naquele dia haverá um grande pranto em Jerusalém, como o pranto de Adadremmon, no campo de Magedon. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 12, 'A terra chorará, família por família: a família da casa de Davide à parte, com suas mulheres à parte; (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 13, 'a família da casa de Natan à parte, com suas mulheres à parte; a família da casa de Levi à parte, com suas mulheres à parte; a família de Semei à parte, com suas mulheres à parte;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 12), 14, 'todas as outras famílias (se lamentarão), família por família, com suas mulheres à parte.');

-- Capítulo 13
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 13, 9);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 1, 'Naquele dia haverá uma fonte aberta para a casa de Davide e para os habitantes de Jerusalém, para se lavarem as manchas do pecado e da impureza.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 2, 'Naquele dia, diz o Senhor dos exércitos, exterminarei do pais (até) os nomes dos ídolos, de forma que deles não haverá mais memória; tirarei dele os falsos profetas e o espírito de impureza.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 3, 'Se alguém intentar ainda inculcar-se por profeta, seu pai e sua mãe, que os geraram, lhe dirão: Tu não viverás, pois que disseste mentira em nome do Senhor.— E seu pai e sua mãe, que o geraram, o traspassarão, quando se tiver metido a profetizar.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 4, 'Naquele dia serão confundidos os (falsos) profetas, cada um pela sua visão, quando profetizarem ; não mais se cobrirão (hipócritamente) com o manto de pêlos para mentirem,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 5, 'mas (cada um deles) dirá: Eu não sou profeta, sou um agricultor, emprego em que me ocupo desde a minha mocidade.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 6, 'Se alguém lhe disser: Que ferimentos São esses entres os teus braços? — responderá: Recebi estes ferimentos na casa dos meus amigos. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 7, 'Ó gládio, levanta-te contra o meu pastor, contra o homem da minha intimidade, diz o Senhor dos exércitos! Fere o pastor, e serão dispersas as ovelhas; voltarei a minha mão mesmo contra os pequeninos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 8, 'Em todo o país, diz o Senhor, haverá dois terços que serão exterminados, que perecerão, e um terço que ficará nele.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 13), 9, 'Farei passar este terço pelo fogo e purificá-lo-ei como se purifica a prata, prová-lo-ei como se prova o ouro. Ele invocará o meu nome, e eu o ouvirei. Dirlhe-ei: Tu és o meu povo — e ele dirá: lavé é o meu Deus. (ver nota)');

-- Capítulo 14
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 14, 21);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 1, 'Eis que está a chegar um dia do Senhor, em que os teus despojos serão divididos, no meio de ti.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 2, 'Juntarei todas as nações para darem batalha contra Jerusalém: a cidade será tomada, as casas serão destruídas, as mulheres violadas; metade da cidade irá para o cativeiro, mas o resto do povo não será lançado fora da cidade.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 3, 'Depois sairá o Senhor e pelejará contra aquelas nações, como peleja no dia do combate. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 4, 'Nesse dia os seus pés pausarão sobre o monte das Oliveiras, que está defronte de Jerusalém para o oriente, e o monte das Oliveiras dividir-se-á em dois pelo meio, ao oriente e ao ocidente, formando uma muito grande abertura: uma metade do monte se separará para o setentrião, e a outra metade para o meio-dia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 5, 'Fugireis para o vale das minhas montanhas, porque o vale das montanhas chegará até Asai; fugireis como fugistes do terramoto nos dias de Ozias, rei de Judá. E virá o Senhor meu Deus, com todos os santos (para punir os inimigos do seu povo).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 6, 'E naquele dia não haverá luz, nem frio nem gelo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 7, 'Será um dia contínuo, conhecido (somente) do Senhor, sem alternativas de dia e de noite: pela tarde não cessará a luz.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 8, 'Nesse dia sairão de Jerusalém águas vivas, metade das quais correrá para o mar do oriente, e a outra metade para o mar do ocidente; correrão durante o estio e durante o inverno. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 9, 'E o Senhor será o rei de toda a terra; naquele dia, Iavé será o único e o seu nome será único.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 10, 'Toda a terra (de Judá) será transformada numa planície, desde Gabaa até Rimmon, ao meio-dia de Jerusalém. (Jerusalém) será exaltada e ocupará o seu lugar, desde a porta de Benjamim até ao sítio da antiga porta, até à porta do Ângulo, e desde a torre de Hananeel até aos lagares do rei.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 11, 'Será habitada e não tornará mais a ser ferida de anátema; Jerusalém será habitada com segurança.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 12, 'A praga com que o Senhor ferirá todas as nações que combaterem contra Jerusalém será esta: Apodrecerá a sua carne, enquanto (ainda) andarem de pé, apodrecer-lhes-ão os olhos dentro das suas órbitas, e apodrecer-lhes-á a língua dentro da boca.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 13, 'Naquele dia haverá grande pânico entre eles excitado pelo Senhor; cada um pegará na mão do seu próximo, levantarão a mão uns contra os outros.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 14, 'Também Judá pelejará em Jerusalém; juntar-se-ão as riquezas de todas as nações circunvizinhas: ouro, prata e roupa em grande abundância. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 15, 'Os cavalos, os machos, os camelos, os asnos e todos os animais que se acharem naqueles arraiais, sofrerão a mesma ruína.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 16, 'Todos os que restarem de todas as nações que vierem contra Jerusalém, irão (a ela) todos os anos adorar o Rei, Senhor dos exércitos, e celebrar a festa dos tabernáculos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 17, 'Qualquer das famílias da terra, que não for a Jerusalém adorar o Rei, Senhor dos exércitos, não receberá chuva.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 18, 'Se a família do Egipto não subir nem vier, não cairá sobre ela (a chuva), mas será ferida da ruína, com que o Senhor atingirá todas as nações que não subirem a celebrar a festa dos tabernáculos. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 19, 'Este será o (castigo do) pecado do Egipto, este o (castigo do) pecado de todas as nações que não subirem para celebrar a festa dos tabernáculos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 20, 'Naquele dia se verá (escrito) nas campainhas dos cavalos: Consagrado ao Senhor. As marmitas na casa do Senhor serão como vasos de aspersão diante do altar.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 14), 21, 'Todas as caldeiras que houver em Jerusalém e em Judá serão consagradas ao Senhor dos exércitos; virão todos os sacrificadores e se servirão delas para nelas cozerem (as carnes consagradas); naquele dia não tornará mais a haver mercador na casa do Senhor dos exércitos. (ver nota)');

