-- undefined (undefined)

-- Capítulo 1
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 1, 23);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 1, 'Paulo, Apóstolo de Jesus Cristo por vontade de Deus, aos santos (que estão em Éfeso) e aos fiéis em Jesus Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 2, 'Graça e paz vos sejam dadas da parte de Deus nosso Pai e do Senhor Jesus Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 3, 'Bendito (seja) Deus e Pai de Nosso Senhor Jesus Cristo, que nos abençoou, do alto dos céus, com toda a bênção espiritual, em Cristo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 4, 'escolhendo-nos nele, antes da criação do mundo, para sermos santos e imaculados, a seus olhos,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 5, 'o qual (também) nos predestinou, no seu amor, para sermos seus filhos adotivos por (meio de) Jesus Cristo, por sua livre vontade,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 6, 'para louvor da sua graça esplendorosa, a qual nos concedeu no muito Amado (Filho).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 7, 'É nele que temos a redenção pelo seu sangue, a remissão dos pecados, segundo as riquezas da sua graça,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 8, 'a qual derramou abundantemente sobre nós, em toda a sabedoria e prudência,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 9, 'tornando-nos conhecido o mistério da sua vontade, que, segundo o seu beneplácito, tinha, desde há muito, estabelecido consigo mesmo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 10, 'para o realizar sua plenitude dos tempos: reunir em Cristo todas as coisas, assim as do céu, como as da terra.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 11, 'Nós, predestinados pelo decreto daquele que opera todas as coisas, segundo o conselho da sua vontade, fomos escolhidos (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 12, 'para servir ao louvor da sua glória, nós, que antes tínhamos esperado em Cristo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 13, 'Nele também vós, tendo ouvido a palavra da verdade, o Evangelho da vossa salvação, e, tendo crido nele, fostes marcados com o selo do Espirito Santo que tinha sido prometido,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 14, 'o qual é o penhor da nossa herança, esperando a plena redenção daqueles que Deus adquiriu, em louvor da sua glória. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 15, 'Por isso, eu também, tendo ouvido qual a fé que tendes no Senhor Jesus e o amor para com todos os santos,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 16, 'não cesso de dar graças (a Deus) por vós, fazendo menção de vós nas minhas orações,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 17, 'para que o Deus Nosso Senhor Jesus Cristo, o Pai de glória, vos dê o espírito de sabedoria e de revelação, para o conhecerdes,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 18, 'iluminando os olhos do vosso coração, para que conheçais qual a esperança a que ele vos chamou, quais as riquezas da glória da sua herança reservada aos santos,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 19, 'e qual é em nós, os que cremos, a suprema grandeza do seu poder, atestado pela eficácia da sua força soberana (em nos converter),'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 20, 'a qual ele empregou em Cristo, ressuscitando-o dos mortos e pondo-o à sua mão direita no céu,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 21, 'acima de todo o principado, potestade, virtude e dominação, acima de todo o nome que é nomeado, não só neste século, mas também no futuro.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 22, 'Pôs debaixo dos seus pés todas as coisas e constituiu-o cabeça de toda a Igreja,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 23, 'que é o seu corpo e o complemento daquele que se completa em todos. (ver nota)');

-- Capítulo 2
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 2, 22);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 1, 'E a vós (deu a vida espiritual), quando estáveis mortos pelos vossos delitos e pecados,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 2, 'nos quais andastes outrora, segundo o costume deste mundo, segundo o príncipe que exerce o poder sobre o ar, o espírito que agora opera nos filhos da desobediência, (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 3, 'entre os quais também todos nós vivíamos outrora, segundo os desejos da nossa carne, fazendo a vontade da carne e dos apetites, e éramos por natureza filhos da ira, como todos os outros.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 4, 'Mas Deus, que é rico em misericórdia, pela extrema caridade, com que nos amou,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 5, 'estando nós mortos pelos pecados, convivificou-nos em Cristo, (por cuja graça fostes salvos).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 6, 'Com ele nos ressuscitou (para uma vida nova) e nos fez sentar nos céus com Jesus Cristo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 7, 'a fim de mostrar aos séculos futuros as abundantes riquezas da sua graça, por meio da sua bondade para conosco em Jesus Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 8, 'Porque pela graça fostes salvos, mediante a fé, e isto não (vem) de vós, porque é um dom de Deus;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 9, 'não (vem) das (vossas) obras (praticadas sem a sua graça), para que ninguém se glorie.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 10, 'Realmente somos obra sua, criados em Jesus Cristo para (fazer) boas obras, que Deus preparou para caminharmos nelas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 11, 'Por isso lembrai-vos, vós, os gentios de origem, chamados incircuncidados pelos que se chamam circuncidados na sua carne por mão de homem,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 12, '(lembrai-vos) que estáveis nesse tempo sem Cristo, separados da sociedade de Israel, estranhos às alianças, sem esperança da promessa e sem Deus neste mundo. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 13, 'Mas agora (que viveis espiritualmente) em Jesus Cristo, vós, que outrora estáveis longe, fostes aproximados pelo sangue de Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 14, 'Porque ele é a nossa paz, ele que de dois povos fez um só, destruindo a parede de inimizade que os separava, (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 15, 'e abolindo na sua carne a lei com os seus mandamentos e prescrições, para formar em si mesmo dos dois um só homem novo, fazendo a paz,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 16, 'e para os reconciliar a ambos, tornados um só corpo, com Deus, por meio da cruz, destruindo a inimizade em si mesmo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 17, 'E assim veio anunciar a paz a vós (gentios), que estáveis longe, e a paz aos (Judeus), que estavam perto,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 18, 'porquanto é por ele que uns e outros temos acesso ao Pai mediante um mesmo Espírito.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 19, 'Vós, pois, já não sois hóspedes, nem adventícios, mas sois concidadãos dos santos e membros da família de Deus,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 20, 'edificados sobre o fundamento dos apóstolos e dos profetas, sendo o mesmo Jesus Cristo a principal pedra angular,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 21, 'sobre o qual todo o edifício (espiritual) bem ordenado se levanta para ser um templo santo no Senhor,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 22, 'sobre o qual vós sois também juntamente edificados para morada de Deus, mediante o Espírito (Santo).');

-- Capítulo 3
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 3, 21);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 1, 'Por esta causa, eu, Paulo, prisioneiro de Jesus Cristo por amor de vós gentios... (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 2, 'se é que tivestes conhecimento da concessão da graça de Deus, que me foi dada para vós:'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 3, 'pela revelação me foi manifestado este mistério, como acabo de expor em poucas palavras. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 4, 'Podeis, lendo-as, conhecer a inteligência que tenho do mistério de Cristo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 5, 'o qual não foi conhecido nas outras gerações pelos filhos dos homens, como agora foi revelado aos seus santos apóstolos e profetas pelo Espírito,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 6, '(isto é, que) os gentios são co-herdeiros (com os Judeus), membros do mesmo corpo e participantes da mesma promessa em Jesus Cristo, mediante o Evangelho,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 7, 'do qual fui feito ministro, segundo o dom da graça de Deus, que me foi comunicada segundo a eficácia do seu poder.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 8, 'A mim, o mínimo de todos os santos, me foi dada esta graça de anunciar entre os gentios as riquezas incompreensíveis de Cristo'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 9, 'e de manifestar o plano deste mistério escondido, desde o principio dos séculos, em Deus, que tudo criou,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 10, 'para que a multiforme sabedoria de Deus seja manifestada por meio da Igreja aos principados e potestades nos céus,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 11, 'conforme a determinação eterna que ele realizou em Jesus Cristo Nosso Senhor,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 12, 'no qual temos segurança e acesso a Deus com confiança, por meio da fé nele.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 13, 'Pelo que vos rogo que não desanimeis por causa das tribulações que sofro por vós: elas são a vossa glória. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 14, 'Por esta causa dobro os joelhos diante do Pai,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 15, 'do qual toda a paternidade nos céus e na terra toma o nome,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 16, 'para que, segundo a riqueza da sua glória, faça crescer em vós o homem interior, pelo seu Espírito,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 17, 'e que Cristo habite pela fé nos vossos corações, de sorte que, arraigados e fundados na caridade,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 18, 'possais compreender, com todos os santos, qual a largura, o comprimento, a altura e a profundidade (do amor de Cristo para com os homens),'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 19, 'e conhecer também aquele amor de Cristo, que excede toda a ciência, de maneira que fiqueis cheios de toda a plenitude (dos dons) de Deus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 20, 'Àquele que é poderoso para fazer todas as coisas mais abundantemente do que pedimos ou entendemos, segundo a virtude que opera em nós,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 21, 'a esse (seja dada) glória na Igreja e em Jesus Cristo, por todas as gerações e por todos os séculos. Assim seja.');

-- Capítulo 4
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 4, 32);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 1, 'Rogo-vos, pois, eu, prisioneiro no Senhor, que andeis de um modo digno de vocação a que fostes chamados,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 2, 'com toda a humildade, mansidão e paciência, suportando-vos uns aos outros por caridade,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 3, 'solícitos em conservar a unidade do espírito pelo vínculo da paz.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 4, 'Há um só corpo e um só Espírito, como também fostes chamados a uma só esperança pela vossa vocação. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 5, 'Há um só Senhor, uma só fé, um só batismo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 6, 'Há um só Deus e Pai de todos, que está acima de todos, que opera em todos e está em todos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 7, 'Mas a cada um de nós foi repartida a graça segundo a medida do dom de Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 8, 'Pelo que (a Escritura) diz: Tendo subido ao alto, levou cativos e distribuiu dons pelos homens (Ps. 67, 19).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 9, 'Ora, que significa subiu, senão que também antes tinha descido aos lugares mais baixos da terra?'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 10, 'Aquele que desceu, é aquele mesmo que também subiu acima de todos os céus para cumprir todas as coisas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 11, 'A uns constituiu apóstolos, a outros profetas, a outros evangelistas, a outros pastores e doutores,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 12, 'para o aperfeiçoamento dos santos, para a obra do ministério, em vista da edificação do corpo de Cristo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 13, 'até que cheguemos todos à unidade da fé e do conhecimento do Filho de Deus, ao estado do homem perfeito, segundo a estatura própria da plenitude de Cristo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 14, 'para que não mais sejamos meninos flutuantes e levados ao sabor de todo o vento de doutrina, pela malignidade dos homens, pela astúcia com que induzem ao erro.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 15, 'Porém, praticando a verdade na caridade, cresçamos de todas as formas naquele que é cabeça, o Cristo. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 16, 'É por ele que o corpo inteiro, coordenado e unido por meio de todos os ligamentos que o servem, segundo uma operação proporcionada a cada membro, opera o próprio crescimento, em ordem à sua edificação na caridade (que é a alma deste corpo ou edifício espiritual).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 17, 'Isto, pois, vos digo e rogo no Senhor: não andeis mais como os gentios, que andam na frivolidade dos seus pensamentos,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 18, 'que têm o entendimento obscurecido (e estão) afastados da vida de Deus pela ignorância que há neles, por causa da ceguira do seu coração,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 19, 'os quais, de consciência embotada, se entregaram à libertinagem, para cometerem apaixonadamente toda a espécie de impureza.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 20, 'Mas vós não aprendestes assim (a conhecer) Cristo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 21, 'se é que ouvistes pregar dele, e fostes ensinados nele, segundo a verdade que está em Jesus,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 22, 'a vos despojardes, pelo que diz respeito ao vosso passado, do homem velho, o qual se corrompe pelas paixões enganadoras,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 23, 'a renovar-vos no vosso espírito e nos vossos pensamentos,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 24, 'e a revestir-vos do homem novo, criado segundo Deus na justiça e na santidade verdadeiras.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 25, 'Pelo que, renunciando à mentira, fale cada um a seu próximo a verdade (Zc. 8, 16), pois somos membros uns dos outros (no mesmo corpo místico que tem Cristo por cabeça).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 26, 'Se vos irardes, não pequeis (Ps. 4, 5); não se ponha o sol sobre a vossa ira. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 27, 'Não deis lugar ao demônio (entregando-vos à ira ) ;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 28, 'aquele que furtava, não furte mais, mas antes ocupe-se, trabalhando com suas mãos em qualquer coisa honesta, a fim de ter que dar ao que está em necessidade.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 29, 'Nenhuma palavra má saia da vossa boca, mas só palavras boas para edificação, de maneira que façam bem aos que ouvem.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 30, 'Não entristeçais (com vossos pecados) o Espírito Santo de Deus, pelo qual fostes marcados com um selo para o dia da redenção.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 31, 'Toda a amargura, animosidade, cólera, clamor e maledicência, com toda a espécie de malícia, seja banida dentre vós.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 32, 'Pelo contrário, sede benignos uns para com os outros, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou por Cristo.');

-- Capítulo 5
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 5, 33);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 1, 'Sede, pois, imitadores de Deus, como filhos muito amados.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 2, 'Andai no amor, a exemplo de Cristo, que nos amou e se entregou a si mesmo por nós a Deus, como oferenda e sacrifício de suave odor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 3, 'Nem sequer se nomeie entre vós a fornicação ou qualquer impureza ou avareza, como convém a santos;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 4, 'nem conversas torpes, nem loucas, nem chocarrices, que são coisas inconvenientes, mas antes (saiam da vossa boca) ações de graças (a Deus).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 5, 'Com efeito, sabei-o bem, nenhum fornicador ou impudico ou avaro, o qual é um idólatra (do dinheiro), terá herança no reino de Cristo e de Deus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 6, 'Ninguém vos seduza com palavras vãs, porque por estas desordens vem a ira de Deus sobre os filhos rebeldes.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 7, 'Não queirais, pois, ter comunicação com eles.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 8, 'Outrora éreis trevas, mas agora sois luz no Senhor. Andai como filhos da luz,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 9, 'porque o fruto da luz consiste em toda a espécie de bondade, de justiça e de verdade.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 10, 'Examinando o que é agradável a Deus,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 11, 'não tomeis parte nas obras infrutuosas (dos filhos) das trevas, mas antes condenai-as.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 12, 'Porque as coisas que eles fazem em secreto, vergonha é até dizê-las.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 13, 'Mas todas as coisas condenadas são postas a descoberto pela luz, e tudo o que é manifestado torna-se luz.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 14, 'Por isso (a Escritura) diz: Desperta, tu que dormes (no sono do pecado); levanta-te dentre os mortos, e Cristo te alumiará (com a sua graça) (Is. 26, 19).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 15, 'Cuidai, pois, Irmãos, em andar com prudência, não como insensatos,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 16, 'mas como circunspectos. Aproveitai o tempo, pois que os dias são maus. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 17, 'Portanto não sejais imprudentes, mas considerai qual a vontade do Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 18, 'Não vos embriagueis com vinho, no qual está a luxúria, mas enchei-vos do Espírito Santo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 19, 'recitando entre vós salmos, hinos e canções espirituais, cantando e salmodiando ao Senhor com todo o vosso coração,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 20, 'dando sempre graças a Deus e Pai, por tudo, em nome de Nosso Senhor Jesus Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 21, 'Sede submissos uns aos outros no temor de Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 22, 'As mulheres sejam sujeitas a seus maridos, como ao Senhor,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 23, 'porque o marido é cabeça da mulher, como Cristo é cabeça da Igreja, seu corpo, do qual ele é o Salvador.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 24, 'Assim como a Igreja está sujeita a Cristo, assim o estejam também as mulheres a seus maridos em tudo (o que não é contra a lei de Deus).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 25, 'Maridos, amai as vossas mulheres, como também Cristo amou a Igreja e por ela se entregou a si mesmo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 26, 'para a santificar, purificando-a no batismo da água pela palavra,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 27, 'para apresentar a si mesmo esta Igreja gloriosa, sem mácula, nem ruga ou coisa semelhante, mas santa e imaculada.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 28, 'Do mesmo modo os maridos devem amar as suas mulheres, como ao seu próprio corpo. O que ama a sua mulher, ama-se a si mesmo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 29, 'Com efeito, ninguém aborreceu jamais a sua própria carne, mas nutre-a e cuida dela, como também Cristo o faz à Igreja,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 30, 'porque somos membros do seu corpo (místico).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 31, 'Por isso deixará o homem seu pai e sua mãe e se unirá a sua mulher; e serão dois numa só carne (Gn. 2, 24). (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 32, 'Grande mistério é este; eu o entendo em relação a Cristo e à Igreja.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 5), 33, 'Por isso também cada um de vós (a exemplo de Cristo, que ama a sua Igreja) ame a sua mulher como a si mesmo, e a mulher respeite a seu marido.');

-- Capítulo 6
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 6, 24);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 1, 'Filhos, obedecei a vossos pais no Senhor, porque isto é justo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 2, 'Honra teu pai e tua mãe, que é o primeiro mandamento que tem promessa,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 3, 'a fim de que sejas feliz e tenhas larga vida sobre a terra (Dt. 5, 16).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 4, 'E vós, pais, não provoqueis à ira os vossos filhos (tratando-os com excessiva severidade), mas educai-os na disciplina e nas instruções do Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 5, 'Servos, obedecei a vossos senhores segundo a carne, com temor e reverência, na sinceridade do vosso coração, como a Cristo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 6, 'não os servindo só quando sob as suas vistas, como por agradar aos homens, mas como servos de Cristo, fazendo do bom coração a vontade de Deus,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 7, 'servindo-os com boa vontade, como se servísseis o Senhor e não os homens.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 8, 'sabendo que cada um receberá do Senhor a paga do bem que tiver feito, quer seja escravo quer livre.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 9, 'E vós, senhores, fazei o mesmo com eles, pondo de parte as ameaças, sabendo que o Senhor, tanto deles como vosso, está nos céus, e que não faz acepção de pessoas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 10, 'De resto, irmãos, fortalecei-vos no Senhor, no seu poder soberano.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 11, 'Revesti-vos da armadura de Deus, para que possais resistir às ciladas do demônio,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 12, 'porque nós não temos que lutar (somente) contra a carne e o sangue, mas sim contra os principados e potestades (do inferno), contra os dominadores deste mundo tenebroso, contra os espíritos malignos (espalhados) pelos ares. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 13, 'Portanto, tomai a armadura de Deus, para que possais resistir no dia mau e ficar de pé depois de ter vencido tudo. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 14, 'Estai, pois, firmes, tendo cingido os vossos rins com a verdade, vestindo a couraça da justiça,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 15, 'tendo os pés calçados de zelo para ir anunciar o Evangelho da paz;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 16, 'sobretudo tomai o escudo da fé, com que possais apagar todos os dardos inflamados do (espírito) maligno;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 17, 'tomai também o elmo da salvação e a espada do espírito, que é a palavra de Deus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 18, 'Fazei continuamente pelo Espírito toda a sorte de orações e de súplicas. Ocupai-vos nisto mesmo com toda a perseverança, rogando por todos os santos (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 19, 'e por mim, para que me seja dado, quando abrir a boca, pregar com liberdade o mistério do Evangelho,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 20, 'do qual eu, mesmo com as algemas, sou embaixador, e para que eu fale corajosamente dele, como devo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 21, 'Para que saibais também o estado das minhas coisas e o que eu faço, de tudo vos informará Tíquico, nosso irmão muito amado e ministro fiel no Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 22, 'Eu vo-lo envio expressamente para que saibais o que é feito de nós e para que console os vossos corações.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 23, 'Paz aos irmãos, caridade e fé, da parte de Deus Pai e da do Senhor Jesus Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 6), 24, 'A graça seja com todos os que amam a Nosso Senhor Jesus Cristo de um modo inalterável.');

