-- undefined (undefined)

-- Capítulo 1
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 1, 30);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 1, 'Paulo e Timóteo, servos de Jesus Cristo, a todos os santos em Jesus Cristo, que estão em Filipos, e aos bispos e diáconos:'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 2, 'graça a vós e paz da parte de Deus nosso Pai e do Senhor Jesus Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 3, 'Dou graças ao meu Deus, todas as vezes que me lembro de vós,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 4, 'fazendo sempre com alegria súplicas por todos vós em todas as minhas orações,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 5, 'por causa da parte que tomastes no desenvolvimento do Evangelho de Cristo, desde o primeiro dia até agora,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 6, 'tendo confiança de que aquele, que começou em vós a boa obra, a completará até ao dia (da vinda) de Jesus Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 7, 'É justo que eu pense assim de todos vós, porque vos tenho no coração, vós todos que, quer nas minhas cadeias quer na defesa e confirmação do Evangelho, sois participantes da minha alegria.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 8, 'Deus me é testemunha de que modo vos amo a todos com a ternura de Jesus Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 9, 'E o que lhe peço é que a vossa caridade cresça mais e mais em compreensão e plena inteligência,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 10, 'para que possais distinguir o melhor, para que sejais sinceros e irrepreensíveis para o dia de Cristo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 11, 'cheios de frutos de justiça por Jesus Cristo, para glória e louvor de Deus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 12, 'Ora eu quero, irmãos, que saibais que todas as coisas passadas comigo têm contribuído mais para proveito do Evangelho.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 13, 'As minhas cadeias por amor de Cristo tornaram-se conhecidas em todo o Pretório e, aliás, em toda a parte,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 14, 'e a maioria dos irmãos, animados no Senhor pelas minhas cadeias, têm tido maior ousadia em anunciar sem temor a palavra de Deus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 15, 'É verdade que alguns pregam a Cristo por inveja e por discórdia, mas outros fazem-no com boa intenção.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 16, 'Estes operam por caridade, sabendo que fui constituído para defesa do Evangelho.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 17, 'Outros anunciam Cristo por espírito de partido, não sinceramente, com o pensamento de acrescentar aflição às minhas cadeias.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 18, 'Mas, que importa? Contanto que Cristo, de qualquer modo, seja anunciado, ou por algum falso pretexto ou com sinceridade, não só nisto me alegro, mas me alegrarei.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 19, 'De facto, sei que isto me resultará em salvação, pela vossa oração e pelo socorro do Espírito de Jesus Cristo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 20, 'segundo a expectação e esperança que tenho, de que em nenhuma coisa serei confundido, mas que, com toda a confiança como sempre, também agora será Cristo glorificado no meu corpo, quer na vida, quer na morte.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 21, 'Com efeito, para mim o viver é Cristo, e morrer é um lucro (porque ficarei mais intimamente unido com ele).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 22, 'Mas, se o viver (mais tempo) na carne me é útil por causa do trabalho (do meu apostolado, que redunda em glória de Deus, então) não sei o que escolher.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 23, 'Estou em aperto por duas partes: tenho o desejo de partir para estar com Cristo, o que é incomparavelmente melhor,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 24, 'mas o permanecer na carne é preferível por amor de vós.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 25, 'E, persuadido disto, sei que ficarei e que permanecerei com todos vós, para vosso proveito e gozo da vossa fé,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 26, 'a fim de que, pela minha volta e presença entre vós, vos dê motivo para vos glorificardes mais em Cristo Jesus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 27, 'Cumpre somente que vos porteis de um modo digno do Evangelho de Cristo, a fim de que, quer eu vá ver-vos, quer esteja ausente, ouça dizer de vós que permaneceis constantes num mesmo espírito, lutando unânimes pela fé do Evangelho,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 28, 'sem terdes medo dos adversários. Isto para eles, é sinal de perdição, como, para vós, de salvação. Tal é a vontade de Deus (que vos dá coragem).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 29, 'Porque a vós vos é dada a graça, em relação a Cristo, não só de crer nele, mas também de sofrer por ele,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 30, 'sustentando o mesmo combate que vistes em mim e que ainda agora ouvistes de mim.');

-- Capítulo 2
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 2, 29);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 1, 'Portanto, se há alguma consolação em Cristo, se algum conforto de caridade, se alguma união de espírito, se alguma ternura e compaixão,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 2, 'tornai completo o meu gozo, tendo todos o mesmo pensar, a mesma caridade, uma só alma, um mesmo sentimento;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 3, 'nada façais por espírito de partido ou por vanglória, mas cada um, por humildade, considere os outros superiores a si,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 4, 'não atendendo (só) aos seus próprios interesses, mas também aos dos outros.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 5, 'Tende entre vós os mesmos sentimentos que se deve ter em Jesus Cristo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 6, 'o qual, existindo na forma (ou natureza) de Deus, não julgou que fosse uma usurpação o seu ser igual a Deus, (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 7, 'mas aniquilou-se a si mesmo, tomando a forma de servo, tornando-se semelhante aos homens e sendo reconhecido, por condição, como homem.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 8, 'Humilhou-se a si mesmo, fazendo-se obediente até à morte, e morte da cruz.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 9, 'Por isso também Deus o exaltou e lhe deu um nome que está acima de todo o nome,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 10, 'de modo que, ao nome de Jesus, se dobre todo o joelho no céu, na terra e no inferno,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 11, 'e toda a língua confesse que Jesus Cristo é Senhor, na glória de Deus Pai.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 12, 'Portanto, meus caríssimos, como sempre tendes sido obedientes, trabalhai na vossa salvação com temor e tremor, não só na minha presença, mas muito mais agora na minha ausência. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 13, 'Porque Deus é o que opera em vós o querer e o executar, segundo o seu beneplácito.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 14, 'Fazei, pois, todas as coisas sem murmuração nem contestações,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 15, 'a fim de serdes irrepreensíveis e sinceros filhos de Deus, sem culpa, no meio de uma nação depravada e corrompida, onde brilhais como astros do mundo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 16, 'conservando a palavra de vida (que vos preguei), para eu ter a glória, no dia (da segunda vinda) de Cristo, de não haver corrido nem trabalhado em vão.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 17, 'Mas, ainda que o meu sangue deva servir de libação sobre o sacrifício e a oferenda da vossa fé, alegro-me e congratulo-me com todos vós.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 18, 'E vós também alegrai-vos e congratulai-vos comigo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 19, 'Espero, no Senhor Jesus enviar-vos brevemente Timóteo, para que eu também fique animado, recebendo noticias de vós,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 20, 'porque não tenho ninguém como ele, unido comigo em sentimentos, que se interesse por vós sinceramente:'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 21, 'Com efeito, todos buscam os seus próprios interesses, e não os que são de Jesus Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 22, 'Sabeis que ele é de uma virtude provada e que, como um filho com o pai, serviu comigo o Evangelho.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 23, 'Espero, pois, mandar-vo-lo, logo que tiver visto o estado das minhas coisas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 24, 'E confio no Senhor que também eu próprio brevemente irei ter convosco.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 25, 'Entretanto, julguei necessário mandar-vos Epafrodito, meu irmão, coadjutor e companheiro de luta, e vosso enviado para me socorrer nas minhas necessidades,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 26, 'pois que ele desejava, por certo, ver-vos de novo a todos e tinha pena de que tivésseis notícia da sua doença.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 27, 'Com efeito, esteve mortalmente enfermo, mas Deus compadeceu-se dele, e não somente dele, mas também de mim, para que eu não tivesse tristeza sobre tristeza.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 28, 'Por isso o enviei mais depressa para que, vendo-o, de novo vos alegreis e eu fique com menor tristeza (sabendo que estais alegres).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 2), 30, 'Efectivamente , pelo serviço de Cristo, chegou às portas da morte, arriscando a própria vida para vos suprir no serviço que vós me não podíeis prestar.');

-- Capítulo 3
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 3, 21);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 1, 'Quanto ao mais, meus irmãos, alegrai-vos no Senhor. A mim não me é penoso, e a vós é salutar, que eu vos escreva as mesmas coisas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 2, 'Guardai-vos desses cães, guardai-vos desses maus operários, guardai-vos desses mutilados. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 3, 'Em realidade, nós é que somos os verdadeiros circuncidados, nós que servimos a Deus em espírito, nos gloriamos em Jesus Cristo e não confiamos na carne, (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 4, 'se bem que também eu poderia ter confiança na carne. Se algum outro, pode confiar na carne, muito mais (o posso) eu,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 5, '(que fui) circuncidado no oitavo dia; (que sou) da geração de Israel, da tribo de Benjamim, (nascido) hebreu de pais hebreus; (que fui), segundo a lei, fariseu;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 6, 'quanto ao zelo, perseguidor da Igreja; quanto à justiça da lei, irrepreensível no meu proceder.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 7, 'Porém, aquelas coisas que (antes) eu considerara como lucro, considerei-as (depois da minha conversão) como perdas por amor de Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 8, 'Sim, na verdade tudo isso tenho por perda, perante o eminente conhecimento de Jesus Cristo, meu Senhor, pelo qual renunciei a todas as coisas e as considero como esterco, para ganhar a Cristo'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 9, 'e ser encontrado nele, não tendo (já) a minha justiça que vem da (observância da) lei, mas aquela que nasce da fé em Jesus Cristo, a justiça que vem de Deus pela fé, (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 10, 'a fim de o conhecer a ele e a virtude da sua ressurreição e a participação dos seus sofrimentos, assemelhando-me à sua morte,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 11, 'para ver se de algum modo posso chegar à ressurreição dos mortos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 12, 'Não que eu tenha já alcançado o prêmio ou seja já perfeito, mas prossigo para ver se de algum modo o poderei apreender, porque eu (que andava fugido e o perseguia) também fui apreendido por Jesus Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 13, 'Irmãos, não julgo ter já alcançado a meta (da perfeição cristã). Mas somente faço uma coisa: esquecendo-me do que fica para trás e avançando para as coisas que estão adiante,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 14, 'prossigo para a meta, para o prêmio da celeste vocação de Deus em Jesus Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 15, 'Todos nós, pois, que somos adultos (na vida cristã), tenhamos estes sentimentos; e, se em algum ponto tendes pensamentos diferentes. Deus também vos esclarecerá sobre isso.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 16, 'Quanto, porém, aquilo a que temos já chegado, continuemos na mesma regra.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 17, 'Sede meus imitadores, irmãos, e ponde os olhos naqueles que andam conforme o modelo que tendes em nós.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 18, 'Porque muitos, de quem muitas vezes vos falei e também agora falo com lágrimas, procedem (com a sua vida sensual) como inimigos da cruz de Cristo :'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 19, 'o fim deles é a perdição, o deus deles é o ventre, e fazem consistir a sua glória naquilo que é a sua vergonha, gostando somente das coisas terrenas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 20, 'Nós, porém, somos cidadãos dos céus, donde também esperamos o Salvador, o Senhor Jesus Cristo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 3), 21, 'o qual transformará o nosso corpo de miséria, fazendo-o semelhante ao seu corpo glorioso, com aquele poder com que pode também sujeitar a si todas as coisas.');

-- Capítulo 4
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 4, 23);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 1, 'Portanto, meus muito amados e desejados irmãos, minha alegria e minha coroa, permanecei assim firmes no Senhor, caríssimos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 2, 'Rogo a Evódia, e suplico a Síntique, que tenham os mesmos sentimentos no Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 3, 'Também te rogo a ti, meu fiel companheiro, que as ajudes a elas que combateram comigo peio Evangelho com Clemente e com os outros meus colaboradores, cujos nomes estão no livro da vida. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 4, 'Alegrai-vos incessantemente no Senhor; outra vez digo, alegrai-vos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 5, 'A vossa afabilidade seja conhecida de todos os homens; o Senhor está perto (e contempla-vos).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 6, 'Não vos inquieteis com nada, mas em todas as circunstâncias manifestai a Deus as vossas necessidades por meio de orações e súplicas unidas à ação de graças.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 7, 'E a paz de Deus, que está acima de todo o entendimento, guarde os vossos corações e os vossos espíritos em Jesus Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 8, 'Quanto ao mais, irmãos, tudo o que é verdadeiro, tudo o que é digno, tudo o que é justo, tudo o que é santo, tudo o que é amável, tudo o que é de bom nome, qualquer virtude, qualquer coisa digna de louvor, seja isto o objeto dos vossos pensamentos.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 9, 'O que aprendestes, recebestes, ouvistes e vistes em mim, isso praticai; e o Deus da paz será convosco.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 10, 'Muito me alegrei no Senhor, porque enfim vi reflorescer os vossos sentimentos a meu respeito; é certo que os tínheis, porém só vos faltava a oportunidade (de os manifestar).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 11, 'Não digo isto, levado pela minha necessidade, porque aprendi a contentar-me com o que tenho.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 12, 'Sei viver nas privações, sei também viver na abundância; a tudo fui habituado : a ter fartura e a passar fome, a estar na abundância e a padecer necessidade.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 13, 'Tudo posso naquele que me conforta.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 14, 'Contudo, fizestes bem em me assistir na minha tribulação (socorrendo-me).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 15, 'Também sabeis, ó Filipenses, que, no princípio da evangelização, quando partida Macedônia, nenhuma igreja me ajudou, abrindo-me uma conta de deve e haver, senão vós somente.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 16, 'Porque até a Tessalonica me mandastes, duas vezes, o que me era necessário.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 17, 'Não é que eu busque dádivas, mas busco o fruto que vá aumentando à vossa conta (diante de Deus).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 18, 'Agora tenho tudo e estou na abundância; estou cheio, depois que recebi de Epafrodito o que me mandastes, como perfume de suavidade, como sacrifício aceite e agradável a Deus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 19, 'O meu Deus, pois, cumpra todos os vossos desejos, conforme as suas riquezas, com glória, em Cristo Jesus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 20, 'Seja dada glória a Deus e Pai nosso, por todos os séculos dos séculos. Assim seja.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 21, 'Saudai todos os santos em Cristo Jesus.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 22, 'Os irmãos que estão comigo vos saúdam. Todos os santos vos saúdam, principalmente aqueles que são da casa de César.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 4), 23, 'A graça de Nosso Senhor Jesus Cristo seja com o vosso espírito.');

