-- undefined (undefined)

-- Capítulo 1
INSERT INTO bible_chapters (book_id, chapter_number, total_verses)
VALUES ((SELECT id FROM bible_books WHERE abbrev = 'undefined'), 1, 25);

INSERT INTO bible_verses (chapter_id, verse_number, text) VALUES
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 1, 'Judas, servo de Jesus Cristo e irmão de Tiago, aos eleitos, amados por Deus Pai e guardados por Jesus Cristo.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 2, 'A misericórdia, a paz e a caridade vos sejam dadas abundantemente.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 3, 'Caríssimos, desejando eu com toda a solicitude escrever-vos acerca da nossa comum salvação, tive necessidade de o fazer, para vos exortar a combater pela fé, que foi dada aos santos, uma vez por todas.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 4, 'Efectivamente, introduziram-se entre vós certos homens ímpios (dos quais está escrito há muito tempo que viriam a cair nesta condenação), os quais trocam a graça do nosso Deus em luxúria, e negam a Jesus Cristo, nosso único Dominador e Senhor.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 5, 'Ora eu quero recordar-vos, embora já saibais tudo, que Jesus, salvando o povo da terra do Egipto, destruiu depois aqueles que não creram;'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 6, 'e os anjos, que não conservaram o seu principado, mas abandonaram o seu domicílio, os reteve com cadeias eternas, nas trevas, para o juízo do grande dia.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 7, 'Assim Sodoma, Gomorra e as cidades circunvizínhas, que com elas se entregaram à luxúria e se abandonaram aos vícios contra a natureza, foram postas por escarmento, sofrendo a pena do fogo eterno.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 8, 'Da mesma maneira também estes, no seu delírio, contaminam a sua carne, desprezam a Dominação (de Cristo) e insultam as glórias.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 9, 'Quando o Arcanjo Miguel, disputando com o demônio, altercava sobre o corpo de Moisés, não se atreveu a proferir contra ele uma acusação injuriosa, mas disse (somente): Reprima-te o Senhor. (ver nota)'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 10, 'Estes, porém, blasfemam de todas as coisas que ignoram, e perdem-se como animais sem razão, em todas aquelas coisas que conhecem naturalmente.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 11, 'Ai deles, porque andaram pelo caminho de Caim, e, por (causa de um aviltante) lucro, precipitaram-se no erro de Balaão e pereceram na rebelião de Coré.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 12, 'Eles são as máculas dos vossos festins, em que se banqueteiam sem respeito, apascentando-se a si mesmos, nuvens sem água, que os ventos levam de uma parte para a outra, árvores de fim de outono, sem fruto, duas vezes mortas, desarraigadas,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 13, 'ondas furiosas do mar, que arrojam as espumas da sua torpeza, estrelas errantes, para quem espessas trevas estão reservadas por toda a eternidade.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 14, 'Também Henoch, o sétimo patriarca depois de Adão, profetizou destes, dizendo: Eis que vem o Senhor, com as suas santas miríades,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 15, 'a fazer juízo contra todos, é a confundir todos os ímpios de todas as obras de impiedade, que cometeram, e de todas as palavras injuriosas, que os pecadores impios têm proferido contra ele (Deus).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 16, 'Eles são uns murmuradores queixosos, que andam segundo as suas paixões, e a sua boca profere coisas soberbas, as quais mostram admiração pelas pessoas segundo convém ao seu próprio interesse.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 17, 'Mas vós, caríssimos, lembrai-vos do que foi predito pelos Apóstolos de Nosso Senhor Jesus Cristo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 18, 'os quais vos diziam : "Nos últimos tempos virão impostores, que andarão segundo as suas paixões, cheias de impiedade."'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 19, 'Estes são os que provocam divisões, seres sensuais que não têm o Espírito (de Deus).'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 20, 'Vós, porém, caríssimos, edificando-vos a vós mesmos sobre o fundamento da vossa santíssima fé, orando no Espírito Santo,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 21, 'conservai-vos no amor de Deus, esperando a misericórdia de Nosso Senhor Jesus Cristo para (alcançar) a vida eterna.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 22, 'Esforçai-vos por convencer os hesitantes,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 23, 'salvai aqueles que podeis arrancar ao fogo. Dos mais, tende compaixão com temor (de serdes contaminados), aborrecendo até a túnica que está contaminada pela sua carne.'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 24, 'Aquele que é poderoso para vos conservar sem pecado e para vos apresentar imaculados e cheios de alegria diante da sua glória,'),
((SELECT id FROM bible_chapters WHERE book_id = (SELECT id FROM bible_books WHERE abbrev = 'undefined') AND chapter_number = 1), 25, 'ao Deus único, Salvador nosso, por Jesus Cristo Nosso Senhor, seja dada glória, magnificência, força e poder, antes de todos os tempos, e agora e por todos os séculos. Amém.');

